### ISSUE TITLE
Zyklisches Aussenden von Nachrichten in Rubriken

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#1]

**Comment by dh3wr** [comment]
Dieser Punkt ist weiterhin offen. Es wäre wirklich gut, wenn die Nachrichten ach zyklisch wiederholt ausgesendet werden. Nicht jeder Skyper ist bei der erstmaligen Aussendung der Nachricht im Empfangsbereich. Idee wäre, ebenfalls über einen Cron-Job vergleichbar mit den Rubriken-Namen auch die Rubriken-Inhalte aussendbar zu machen.

**Comment by Taronyu** [comment]
Das wäre auch für wöchentliche Probealarme oder Ähnliches nutzbar.

**Comment by Taronyu** [comment]
Siehe #68
