### ISSUE TITLE
Mögliche Anwendungen im Amateurfunk erarbeiten

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#10]
Existieren des Weiteren Einsatzmöglichkeiten außerhalb des Amateurfunks? Zumindest darf ja jeder die Funkrufe empfangen...

**Comment by dh3wr** [comment]
Da hier wohl nichts mehr dieses Jahr kommen wird, mache ich das mal zu.
