### ISSUE TITLE
Uhrzeit?

### ISSUE THREAD

**Issue by dg5mm** [DecentralizedAmateurPagingNetwork/Core#100]
Zu Zeiten des Funkrufmaster-Zeitalters wurde ja UTC-Zeit aufs Display gezaubert, aktuell verwenden wir ja kuechenuhr. Ist das beabsichtigt (noch zu aendern)?

**Comment by Taronyu** [comment]
Ist auf UTC umgestellt.

**Comment by dh3wr** [comment]
Tja, das war immer eine zweischeidige Sache. Läuft's auf UTC, fragen mich die Menschen: ``Warum geht die Uhrzeit denn 2 Stunden nach`` Macht man nicht UTC, wollen die Leute UTC. Aber gut, fahren wir auf UTC, dann haben die Leute auch die richtige Zeit, auch bei Zeitumstellungen. Der Skyper hat das nämlich im Frühling ignoriert.
