### ISSUE TITLE
Log Ausgabe Interpretation

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#107]
``12:20:18.058 [DefaultQuartzScheduler_Worker-10] INFO  org.dapnet.core.transmission.TransmissionManager - Rubric sent to transmitters.
``
heißt dass der Name gesendet wurde oder der Inhalt? Wenn Name, vielleicht auch den Namen angeben?

**Comment by Taronyu** [comment]
Das bezieht sich nur auf den Namen, die News werden anders gesendet.
