### ISSUE TITLE
Cross-Ref: PUT von Node übernimmt nicht SUSPENDED State Wunsch

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#108]
Das ist schon nötig, um ggf. die Mehrheit wiederzugewinnen, wenn viele unknown sind.

https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/86

**Comment by Taronyu** [comment]
Die alten Daten werden jetzt nur noch übernommen, wenn der Knoten online
ist.

**Comment by dh3wr** [comment]
aha. Das forced-suspended setzen wäre aber schon schön. Von mir aus auch nur aus, die Koordinaten sind egal. Wenn bei einem Netzwerk-Ausfall alle down sind und man will seinen Knoten neu starten und Änderungen machen, muss man sonst manuell in der State.json die states auf SUSPENDED setzen.

**Comment by Taronyu** [comment]
Wenn ich gar keine Daten sperre, kann man halt einen Knoten, der Online ist, als Offline markieren und die IP manipulieren. Das wird bis zum nächsten Reconnect dann auch nicht mehr repariert.

Eigentlich muss der Core beim Start alle anderen Knoten von alleine auf SUSPENDED setzen und dann das State-Update abwarten.

**Comment by dh3wr** [comment]
ah, das wäre noch besser

**Comment by Taronyu** [comment]
Ich mach hier dann erst mal wieder auf.

**Comment by Taronyu** [comment]
Der Core setzt beim Start nun alle Nodes auf SUSPENDED. Damit müsste der dann auch starten und sich einen State abholen können. Und wenn er der einzige Knoten ist, hat mein kein Quorum-Problem.

**Comment by dh3wr** [comment]
Sehr gut!
