### ISSUE TITLE
API für Statistiken

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#11]
Z. B. so https://brandmeister.network/?page=callstats

**Comment by MarvinMenzerath** [comment]
Momentan gibt es im Web-Interface auf der Startseite einen kleinen Teil mit Statistiken. Diese Werte werden nach dem Abruf der jeweiligen Daten selbst berechnet und dort angezeigt.

Schöner wäre es allerdings, wenn der Core bereits eine API (z.B. unter `/stats`) anbieten würde, die (auch ohne Authentifizierung) Statistiken wie die Anzahl der Rufe, Nachrichten, Sender (online / offline), Knoten (online / offline), Nutzer, etc. ausgeben würde.

Damit würde man zumindest beim ersten Laden der Seite ein wenig Traffic und Wartezeit einsparen...

**Comment by Taronyu** [comment]
Das klingt sinnvoll, ich nehme mich der Sache mal an.

Am 02.03.2017 12:51 schrieb "Marvin Menzerath" <notifications@github.com>:

**Comment by Taronyu** [comment]
Unter `/stats` sind nun ein paar Daten abrufbar.

**Comment by MarvinMenzerath** [comment]
Danke!
