### ISSUE TITLE
Löschen eines Nodes liefert "Internal Server error"

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Core#112]
Ich habe versucht, einen Node zu löschen, der seit Erstellung vor 3 Monaten immer nur suspended ist und keinen Sender versorgt (der Ausfall eines weiteren Nodes führte wiederholt zu Minority Group). Sowohl das Webinterface als auch curl liefern "500 Internal Server Error". Hängt möglicherweise mit #108 zusammen.

**Comment by Taronyu** [comment]
Müssten wir mal testen, ob mein commit das repariert hat.
