### ISSUE TITLE
Problem mit neu erstelltem Core

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#117]
Ich habe on3dhc neu angelegt und per Webinterace auf SUSPENDED gesetzt. Dann habe ich den Core dort gestartet.
Es lief auch alles, der State wurde übertragen, aber der Knoten war nicht ONLINE auf db0sda.
````
dapnet@dapnet:/opt/dapnet/Core/local$ java -jar ../target/dapnet-core.jar
15:38:47.798 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNETCore Version 1.1.3.8-SNAPSHOT ...
15:38:47.800 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
15:38:47.873 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
15:38:47.889 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.5.Final
15:38:47.934 [main] WARN  org.dapnet.core.cluster.ClusterManager - State file not found.
15:38:47.936 [main] WARN  org.dapnet.core.cluster.ClusterManager - Creating new empty State
15:38:52.422 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0sda, db0wa, db0ffl, db0fa, db0rta, on3dhc]
15:38:52.452 [ViewHandler] INFO  org.dapnet.core.model.State - Successfully wrote state to file
15:38:52.676 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.cluster.MessageListener - Receiving State from other Node
15:38:53.042 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.model.State - Successfully wrote state to file
15:38:53.042 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.cluster.MessageListener - State successfully received
15:38:53.042 [main] INFO  org.dapnet.core.DAPNETCore - Starting SchedulerManager
15:38:53.094 [main] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully started
15:38:53.095 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
15:38:53.589 [main] INFO  org.dapnet.core.rest.RestManager - RestApi successfully started.
15:38:53.589 [main] INFO  org.dapnet.core.DAPNETCore - Starting Transmitter Server
15:38:53.676 [main] INFO  org.dapnet.core.transmission.TransmitterServer - Server started on port: 43434
15:38:53.676 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore started
15:39:00.034 [DefaultQuartzScheduler_Worker-1] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
15:39:42.143 [ShutdownHook] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNETCore ...
15:39:46.463 [ShutdownHook] INFO  org.dapnet.core.transmission.TransmitterServer - Server stopped.
15:39:46.536 [ShutdownHook] INFO  org.dapnet.core.rest.RestManager - RestApi successfully stopped.
15:39:46.537 [ShutdownHook] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully stopped
15:39:46.541 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
15:39:46.541 [Incoming-1,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.cluster.RpcListener - UpdateNodeStatus on3dhc to SUSPENDED: OK
15:39:49.739 [ShutdownHook] INFO  org.dapnet.core.model.State - Successfully wrote state to file
15:39:49.740 [ShutdownHook] INFO  org.dapnet.core.DAPNETCore - DAPNETCore stopped
````

Nach einem restart schon. Fehlt evtl. die "ich bin online-Meldung" beim ersten Mal an das Cluster?

````
15:40:40.713 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.5.Final
15:40:43.734 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0sda, db0wa, db0ffl, db0fa, db0rta, on3dhc]
15:40:43.754 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of on3dhc from SUSPENDED to ONLINE
15:40:43.754 [ViewHandler] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
15:40:43.788 [ViewHandler] INFO  org.dapnet.core.model.State - Successfully wrote state to file
15:40:43.837 [Incoming-2,DAPNET1.1.3.8-SNAPSHOT,on3dhc] INFO  org.dapnet.core.cluster.MessageListener - Receiving State from other Node
````

**Comment by Taronyu** [comment]
Das kann sein. Wenn ich das recht in Erinnerung habe, dann war das Join eh
nicht ganz so trivial vom Ablauf. Muss ich morgen mal reingucken.

**Comment by dh3wr** [comment]
Selbst nach einem Restart kommt die "online" Meldung nicht mehr. Die Verbindung steht aber. Es scheint die Aktualisierung des States nicht an der Cluster gesendet zu werden.

**Comment by Taronyu** [comment]
So richtig habe ich die Stelle auch noch gar nicht gefunden, wo das passieren soll.

**Comment by dh3wr** [comment]
Hat sich erledigt. Grund war, dass String1@dapnet bei der Node-Config eingetragen war, aber String2 der Name des Nodes bei den anderen Nodes in der State.json war. Sorry. Vielleicht aber eine Ausgabe einbauen wie: Your Node ist not registered. Die Verbindung bestand nämlich trotzdem. Es wird wohl nur das Shared Secret überprüft.

**Comment by Taronyu** [comment]
Muss ich mir mal ansehen, ob das geht. Das Shared Secret Gedöns läuft ja komplett über jgroups, da haben wir keine Aktien drinnen.

**Comment by dh3wr** [comment]
D.h. die Nodes Liste wird nicht wirklich beachtet? Es findet dann nur kein State Update statt, wenn man nicht in der Liste ist als joinender node?

**Comment by Taronyu** [comment]
Wir hatten das Problem ja, dass der Master sich dann auch beim Client authentifzieren wollte, der Client aber noch gar keinen State hatte, gegen den er prüfen könnte. Daraufhin sind wir dann auf den Shared Key umgestiegen. Eventuell kann man nach dem Empfang des States gucken, ob der eigene Name im State auftaucht.

**Comment by dh3wr** [comment]
Kann der neue Node, bei dem der neue Node sich anmeldet, nicht vor dem Join prüfen, ob der neue Node auch in der Node-Liste ist und sonst das Anmelden verweigern? Das kann ja alles auf dem bestehenden Node geschehen, der ja seinen State schon hat.

**Comment by Taronyu** [comment]
Es gibt keinen Handler, der vor dem Join aufgerufen wird. Man müsste die Authentifizierung dann wieder komplett selbst implementieren. So auf die Schnelle sehe ich nur die Möglichkeit, nach dem Statetransfer auf dem neuen Knoten zu prüfen, ob der Name im State vorhanden ist.

**Comment by Taronyu** [comment]
Ich habe mal einen Workaround eingebaut, der nach dem Statetransfer prüft, ob der aktuelle Knotenname im empfangenen State existiert und falls nicht wird der Core mit einer entsprechenden Meldung beendet.
