### ISSUE TITLE
An welche Sender werden die Rubriken-Namen gesendet

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#119]
Rubiken haben ja TX-Groups als Eigenschaft. Wird vom Cronjob der Name auch nur an die TXe geschickt, die auch in der TX-Gruppe der entsprechenden Rubrik sind? Zur Zeit klagt do5jwa, dass er die DXCluster-Gruppennamen nicht bekommt, auch wenn er nun in der entsprechenden TXGruppe eingetragen ist.

**Comment by 7h0ma5** [comment]
Ich glaube schon, und das macht eigentlich auch Sinn. So gibt es zum Beispiel die `metar-dl-nw` Rubrik mit dem Titel "METAR NRW", die nur von den Sendern in dl-nw ausgestrahlt wird. Parallel dazu kann man dann in anderen Bundesländern Rubriken mit der gleichen Nummer aber anderen Titeln haben.

**Comment by Taronyu** [comment]
Ja, das geht nur an die eingetragenen Sendergruppen.

**Comment by dh3wr** [comment]
OK danke für die Info. Hat sich geklärt. Das Problem war zwischen Stuhl und Bildschirm.
