### ISSUE TITLE
Enhancement: Nachrichtenprioritäten

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Core#122]
Man könnte Nachrichten mit drei Prioritäten einführen, also
1. Dringend (Notrufe, Zeitsignal)
2. Normal (Personenrufe)
3. Hintergrund (Rubriken)

Das wäre zunächst nur ein Flag, der an den Unipager übertragen wird. Im Unipager könnte das dann über drei Queues realisiert werden, in welche die Nachrichten einsortiert werden. Die "Dringend"-Queue wird zuerst abgearbeitet, sobald die leer ist kommt "Normal" und dann "Hintergrund".

**Comment by 7h0ma5** [comment]
Das ist sehr sinnvoll. Zusätzlich könnten die Nachrichten auch noch eine Art Ablaufzeit bekommen, nach der sie verworfen werden, wenn sie bis dahin nicht versendet wurden. Das wäre zum Beispiel für DX-Cluster-Nachrichten interessant, damit keine alten Spots die Queue belegen.

**Comment by Taronyu** [comment]
Die Übertragung der Priorität ist vom Netzwerkprotokoll nicht vorgesehen, wenn ich das richtig gesehen habe. Das sehe ich erst mit der Umstellung auf ein eigenes Protokoll kommen, wobei ich mir dann für den Proxy noch was überlegen müsste, wie der damit umgeht.

**Comment by dh3wr** [comment]
Och den proxy können wir erstmal raus lassen, dir OMs sollen mal auf IP umstellen wenn sie das Feature haben wollen

**Comment by DL9DAK** [comment]
Hinweis: Im kommerziellen bzw. BOS POCSAG nutzt man die RIC Subadressen A ... D für die Priorisierung, siehe Issue #149 „Anwendung RIC-Subadressen“.

**Comment by dj7lc** [comment]
Peter, Danke für den Hinweis, damit ist aber das Problem nicht gelöst. Fortführung der Diskussion unter
https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/157
