### ISSUE TITLE
CW Callgeber in PA gefragt

### ISSUE THREAD

**Issue by pe2kmv** [DecentralizedAmateurPagingNetwork/Core#124]
Die geänderte Gesetzeslage in PA erfordert explizit eine periodische Identifizierung des Senders in Phone oder CW. Identifizierung wie vorher z.B. über AX25, oder in diesem Fall POCSAG reicht leider nicht mehr aus.

Ist es möglich einen CW Callgeber zu implementieren, der gegebenenfalls über die Unipager-Oberfläche geschaltet werden kann (vielleicht noch mit einstellbarem Intervall)?

**Comment by Taronyu** [comment]
Das dürfte direkt im Sender besser aufgehoben sein. Dass der Core das Rufzeichen jetzt als Call abschickt, ist eigentlich auch eher suboptimal. Für CW oder Phonie ist weder der Core noch das Netzwerkprotokoll ausgelegt.

**Comment by Taronyu** [comment]
Ich habe mal ein Issue im Unipager aufgemacht.
