### ISSUE TITLE
Core Version und github-Commit in der Node-Übersicht anzeigen als read only

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#127]
Um Fehlerfälle im Cluster leichter identifizieren zu können wäre es schön, wenn man schauen kann, welche Version auf welchem Node läuft. Könnte man die Versionsnummer aus der pom.xml und ggf. auch den github commit hash als Readonly über die API ausgeben bei den Nodeeigenschaften?

**Comment by dh3wr** [comment]
Ist jetzt drin und geht, oder?

**Comment by Taronyu** [comment]
Das ist bisher nur in experimental enthalten. Wir haben das AFAIK noch nicht getestet.

**Comment by dh3wr** [comment]
Müsste schon getestet sein, jedenfall ist es im Web zu sehen:
![grafik](https://user-images.githubusercontent.com/16710361/30022063-e9821e78-9169-11e7-88c8-e9de90efa0a2.png)

**Comment by Taronyu** [comment]
Okay, das hatte ich nicht mehr auf dem Schirm. Dann können wir eigentlich zu machen, den commit hash baue ich irgendwann mal ein.
