### ISSUE TITLE
Sender owner should be able to transmit rubric names on demand

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#132]
Es wäre schön wenn transmitter Besitzer manuell die Aussendung der Rubriken Namen für Ihren Sender auslösen könnten. Dazu vielleicht einen neuen Rest Endpunkt einführen und auf ownership prüfen vor der Ausführung.

**Comment by Taronyu** [comment]
In `experimental` ist eine erste Implementierung zu finden. Ein `GET` auf den Pfad `transmitterControl/sendRubricName/<Transmittername>` führt die Operation aus, sofern man als Owner angemeldet ist.

**Comment by dh3wr** [comment]
Ich installiere mal den aktuellen experimental auf dapnet.db0sda.ampr.org, dann kann man mal testen.

**Comment by dh3wr** [comment]
Geht, kann in den Master-Branch überführt werden.

**Comment by Taronyu** [comment]
Ist zusammengeführt.

**Comment by dh3wr** [comment]
Vielleicht ein neues Release? Dann deploye ich das auf allen Nodes

**Comment by Taronyu** [comment]
Neues Release ist hochgeladen: v1.1.3.9

**Comment by dh3wr** [comment]
Deploye ich heute Nachmittag

**Comment by dh3wr** [comment]
done
