### ISSUE TITLE
Nicht-Admins bekommen unter Callsign ihre eigene Nummer nicht angezeigt

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#136]
Wenn man nicht-Admin ist, aber ein Owner eines Callsigns ist, bekommt man die Pager-Nummer in der /callsign-Liste nicht angezeigt. Beim explizieten Abruf allerdings schon.

ToDo: Pager-Nummern auch in der Übersicht für die Callsigns ausgeben, zu denen man Owner ist.

**Comment by Taronyu** [comment]
So wie die Serialisierung bei der Gesamtübersicht funktioniert, ist das technisch nicht möglich. Der Owner kann nur beim Einzelabruf bestimmt werden. Bei der Übersicht bekommt der Serialisierer die komplette Liste übergeben und für die Liste gibt es keinen Owner, daher wird die Berechtigung nur auf User oder Admin geprüft.

**Comment by Taronyu** [comment]
Ich habe mir das jetzt noch einmal angesehen. In der ExclusionStrategy bekommt man nur einen Feldnamen, aber keine Instanz von dem Objekt. Da besteht also keine Möglichkeit, irgendwie noch ein Owner-Check einzubauen. Vermutlich müsste man das ganze Objekt mit einem Custom-Serializer/Deserializer verarbeiten.
