### ISSUE TITLE
Sender-Identifikation zur Erfüllung der Gesetzgebung

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#14]
Laut Amateurfunkgesetz muss sich jeder Sender alle 10 Minuten identifizieren. Dazu kann man die Rubrik 99 nehmen, und dort kann jeder Sender auf Nachricht 1 seine Rufzeichen aussenden und ggf. noch ein paar Statusinfos hinzufügen.

**Comment by dj7lc** [comment]
Ich schlage vor, diese Aufgabe an den RasPager oder RustPager zu übertragen.
https://github.com/rwth-afu/RustPager/issues/16

**Comment by DanielSialkowski** [comment]
Gehört meiner Meinung nach auch in den Core. Ließe sich analog zur Zeitaussendung umsetzen, sodass alle paar Minuten eine Nachricht ausgesendet wird. Frage ist nur wie die Identifikation gesendet werden soll. Als Nachricht wo sie jederzeit von anderen Sendern überschrieben werden kann? Als einfacher Ruf um die gesetzliche Regelung zu erfüllen, die jedoch von keinem Pager empfangen werden kann (da Pager Nummer nicht übereinstimmt)?

**Comment by dh3wr** [comment]
Früher gab es die Rubrik 99, in der jeder Master seine verbundnen Slave bekanntgab. Das kann natürlich auf Grund der vielen an einem Master hängende Slaves mehr als 10 sein, was wieder zu Problemen führen kann.

Der Nutzen für den User war, dass er bei Abonnierung der Rubrik 99 sehen konnte, von welchem Sender er etwas empfängt. Im Einzugsbereich von Slaves unterschiedlicher Master war das allerdings auch wieder überschneidungsbehaftet.

Meiner Meinung nach also alles doof. Vielleicht nehmen wir einfach die Gruppe 99 und Nachricht 1 aus den 10 enthält bei jedem Sender sein Rufzeichen, seine Admins, die Sendeleistung und die Koordinaten. Dann kann man die Gruppe abonnieren und sieht halt wechselnd beim Empfang mehrerer Sender, wer denn gerade empfangen wird.
Die Nachrichten 2 bis 10 in Gruppe 99 könnten mit anderen Statistik-Infos gefüllt werden. Was genau würde ich lieber in einem eigenen Issue besprechen.

**Comment by dj7lc** [comment]
Das erscheint mir noch zu kompliziert. Wenn jeder Core eine Liste seiner Sender hat, kann er alle 10 Minuten (Timer-Event) einmal drüberiterieren und an die RIC 1234567 einen Text wie "FUNKRUFSENDER DB0SDA" schicken.

**Comment by dh3wr** [comment]
ok, insb. weil die Rubriken-Nachricht ja nicht an eine Sendergruppe, sondern an alle Sender einzeln mit unterschiedlichen Inhalten ausgehen muss. Vielleicht gibt es noch eine RIC, die da besser für geeignet ist? Vielleicht eine Broadcast-RIC wie bei der Uhrzeit, die aber nicht empfangen wird von Skypern? Oder sonst 000000?

**Comment by Taronyu** [comment]
Aussendung des Transmitternamens erfolgt nun periodisch an eine konfigurierbare Adresse (im Transmitter festzulegen; standardmäßig 1). Das Intervall kann angepasst werden, ohne weitere Angabe erfolgt die Aussendung alle 10 Minuten.
