### ISSUE TITLE
Anonymous display of transmitter details and map?

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#140]
Es gibt eine Anfrage / Vorschlag, ob man die Sender-Karte nicht auch ohne Anmeldung anzeigen lassen könnte... Wäre das einfach möglich? Dazu müsste ja wohl nur die Transmitter-Liste abgerufen werden können, oder? Write-Zugang soll natürlich unterbunden sein.

**Comment by Taronyu** [comment]
Ich kann die Transmitterliste natürlich einfach für anonym freischalten. Steht da was drin, was man nicht sehen sollte? Die Owner wären vermutlich sichtbar, wenn man die nicht filtert.

**Comment by dh3wr** [comment]
Moin, Im Grunde kann alles anonym ausgegeben werden, außer dem Auth-Key. Der ist aber wahrscheinlich schon jetzt nur für owner und admins freigegeben.

**Comment by Taronyu** [comment]
Ich habe die Transmitter für alle freigegeben, der Hash wird nicht angezeigt.

**Comment by dh3wr** [comment]
Schon implementiert auf der Startseite von hampager.de mit Kartenansicht.
