### ISSUE TITLE
Don't give Email Adresses out for non-admin users

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#141]
Es gab Datenschutzbedenken. Vielleicht können wir bei Non-Admin-Usern nur die Anzeige der eigenen Email-Adresse ermöglichen? Also gar nicht über die REST-API verteilen?

**Comment by Taronyu** [comment]
Eigentlich ist für Nicht-Admins die Emailadresse des User-Objekts bereits ausgeblendet (außer man ist Owner). Wo ist denn das aufgefallen?

**Comment by dh3wr** [comment]
Ist nicht mehr aufgetreten.
