### ISSUE TITLE
Enhancement: Zeit für Swissphone 

### ISSUE THREAD

**Issue by dk4pa** [DecentralizedAmateurPagingNetwork/Core#145]
Das Aussenden von Uhrzeit und Datum für Swissphone Pager.

Der Befehl zum setzen von Datum und Uhrzeit lautet:
XTIME=2300291117XTIME=2300291117

Setzt Uhrzeit auf 23:00 Uhr und Datum auf 29.11.17 
Getestet hier mit einem BOSS925 

Das X steht für ein Startzeichen dass im Pager programmiert werden muss.
Weiter muss im Pager eine OAP RIC programmiert werden, an die der Befehl gesendet wird.
Diese sollte dann festgelegt werden.

Vy73 Stefan

**Comment by dh3wr** [comment]
Was ist denn das Startzeichen, auf das wir uns einigen?
Ist dass dann ein alphanum. Ruf? Die Skyper-Uhrzeit kommt ja per numerischem Ruf.
Als RIC sollten wir eine unter 9999 nehmen.

**Comment by dk4pa** [comment]
Ich würde hier das Startzeichen X übernehmen.

Ja es wurde per Alphanumerischen Ruf aus dem UniPager Interface gesendet.
Nachrichten werden hier mit der Unteradresse A gesendet korrekt?
Die Subadressen lassen sich ja nicht einzeln auswählen.

Skyper hat ja als Zeit RIC 2504, man könnte ja hier einfach wenn nicht belegt durch andere Funktionen 2505 nehmen.

Das Aussenden muss auch nicht minütlich erfolgen, da der Pager keine Zeit benötigt um zu Emofangen wir der Skyper.
Mein Vorschlag wäre hier einmal am Tag evtl. 00:00 Uhr

**Comment by dh3wr** [comment]
oder 1Mal/Stunde. Ist ja nur ein Ruf

**Comment by dk4pa** [comment]
Von mir aus gerne auch 1Mal/Stunde

**Comment by dk4pa** [comment]
Bisher löse ich es so.
Das Script wird stündlich aufgerufen, jedoch ohne Prio.

Deshalb sollte die Aussendung parallel zur Skyper Zeit laufen. 

Als Callsign wurde swiss_oap mit der RIC 0165856 eingerichtet.

https://github.com/dk4pa/dapnet-swissphone

**Comment by dh3wr** [comment]
Ich habe das mal quick&dirty implementiert. Es wäre besser gewesen, eine neue Klasse für die Swissphones anzulegen und dann die Send-Time Routine sowohl für Typ "Skyper" als auch "Swissphone" zu überschreiben. Dazu kann ich aber nicht genug Java...
Siehe b383e8a1e250fb24f3c69d970009a2dd4bd05dc4

**Comment by Taronyu** [comment]
Ist jetzt im refactoring branch umgesetzt.
