### ISSUE TITLE
Rubiken-Namen werden auch an Sender, die nicht in der TXGruppe sind, gesendet

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#152]
Beispiel: Rubric ``odl-bw`` hat TX-Gruppe: ``dl-bw``
In ``dl-bw`` ist ``db0wa`` als Sender aber nicht enthalten. Trotzdem bei manueller Sende-Auslösung der Gruppen-Namen:
````Dec 23 19:59:47 dapnet java[23114]: 19:59:47.656 [Incoming-2,DAPNET1.1.3.10,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - Rubric odl-bw sent to transmitter db0wa````

**Comment by Taronyu** [comment]
Hmm, hab mir das mal angesehen:
```
// Im Scheduler Job:
clusterManager.getState().getRubrics().values().forEach(r -> transmissionManager.handleRubric(r));

// transmissionManager.handleRubric(r)
PagerMessage message = protocol.createMessageFromRubric(rubric);
transmitterManager.sendMessage(message, rubric.getTransmitterGroups());

// rubric.getTransmitterGroups() mappt auf transmitterGroupNames
ConcurrentMap<String, TransmitterGroup> groups = state.getTransmitterGroups();
ArrayList<TransmitterGroup> result = new ArrayList<>();
for (String transmitterGroup : transmitterGroupNames) {
	TransmitterGroup g = groups.get(transmitterGroup.toLowerCase());
	if (g != null) {
		result.add(g);
	}
}

// Senden der Rubriknamen an die Sender
public void sendMessage(PagerMessage message, Collection<TransmitterGroup> groups) {
	getTransmitterNames(groups).forEach(n -> sendMessage(message, n));
}

// Abrufen der betroffenen Sender
private static Set<String> getTransmitterNames(Collection<TransmitterGroup> groups) {
	Set<String> selected = new HashSet<>();
	for (TransmitterGroup g : groups) {
		g.getTransmitterNames().forEach(t -> selected.add(t.toLowerCase()));
	}

	return selected;
}
```
Das sieht eigentlich so aus, wie ich das jetzt erwarten würde. Es werden die Sendergruppen aus den Rubriken geladen und daraus anschließend die Namen der Sender extrahiert. An diese Sender wird dann die Nachricht mit dem Rubrikennamen geschickt. Wie hast du denn das manuelle Senden getriggert?

**Comment by dh3wr** [comment]
![grafik](https://user-images.githubusercontent.com/16710361/46863299-575bbe00-ce17-11e8-83b0-c0b16ff3606c.png)

**Comment by dh3wr** [comment]
https://hampager.de/api/transmitterControl/sendRubricNames/ab3qv  als Beispiel
