### ISSUE TITLE
Datenkonsistenz von Sender-Status beim Zerfall des Clusters

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#155]
Szenario:

- Sender an Node 1 im Status ``online``
- Node 1 fliegt aus dem Cluster
- Nodes 2-n zeigen Sender weiterhin als ``online`` an.

Lösung: Wenn ein Node aus dem Cluster fliegt, den Sender-Status im restlichen Cluster resetten bzw, auf offline stellen. Wenn sich der Sender dann automatisch an einem anderen Node anmeldet, wird der Status ja wieder auf online gesetzt.

**Comment by Taronyu** [comment]
Ich habe im refactoring Branch mal was dafür gebaut
