### ISSUE TITLE
News Menü

### ISSUE THREAD

**Issue by DL9DAK** [DecentralizedAmateurPagingNetwork/Core#156]
Hallo, seit einigen Tagen sehe ich auf dem DAPNET Web-Portal kein „News“ Menü mehr zum Absenden einer Rubriknachricht. Wo ist denn diese geblieben?

**Comment by dk4pa** [comment]
Hallo Peter,
die Bezeichnung wurde geändert.
Du findest die News nun unter Rubric Content. 
Hier ist auch die Möglichkeit unter New Rubric Content eine Nachricht an eine Rubric auszusenden.
Ich hoffe ich konnte dir hiermit helfen?
![content](https://user-images.githubusercontent.com/25099739/34894371-0b92e7b0-f7d9-11e7-8ffc-59467b4e2a0d.jpg)

vy73, Stefan dk4pa

**Comment by DL9DAK** [comment]
Prima - danke. Wäre es nicht sinnvoll auf der Seite auf Veränderungen und Ergänzungen (wie Support Ticket System etc.) hinzuweisen?

**Comment by dk4pa** [comment]
Moin,
sehr gerne. Ich denke das Thema passt eher zu [https://github.com/DecentralizedAmateurPagingNetwork/Web](url)

Weiter gibt es hier bereits dazu ein Issue.
https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/129

Auf der Website hampager.de ist die Änderung bereits geschehen.

Viele Grüße
Stefan, dk4pa 

![7c0ef968-248f-4fc8-b467-1a593e266a1e](https://user-images.githubusercontent.com/25099739/34903870-ae62c292-f83a-11e7-9b0c-c6e6c78383ca.jpeg)

**Comment by dh3wr** [comment]
@DL9DAK Siehe auch hier: https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/d52b22fd348e92f778b853982bc37c4334d5b397  Da ist eine mehr Aufmerksamkeit erregende Darstellung des DokuWikis enthalten. Wird mit dem nächsten Web-Update ausgerollt.
