### ISSUE TITLE
Zivilschutz in DAPNET (Johannes Gierlach)

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#16]
Hallo Ralf,

heute war großer Zivilschutz-Probealarm im Rheinland, das hat mich auf 
eine Idee gebracht: Wäre es nicht möglich, Warnungen vom Bundesamt für 
Bevölkerungsschutz direkt über DAPNET zu verbreiten? Vom "Amt" aus 
werden sowieso Alarmierungen per Mail rausgeschickt. Wenn DAPNET E-Mails 
annehmen kann, haben wir schon eine Schnittstelle. Sobald das alles 
funktioniert könnte man die zuständige Stelle mal mit RWTH-Briefkopf 
anschreiben und nachfragen. Was denkst Du über diese Idee?

Vy73 Johannes

**Comment by dh3wr** [comment]
Hallo Johannes,

Interessante Idee. Dazu müsste man ein Interface von POP3 auf REST-API schreiben. Man könnte sich z.B. eine Email-Adresse bei GMX machen und dorthin die Zivilschutz-Emails abonnieren. Oder es gibt noch andere Möglichkeiten, an die Daten zu kommen. Bist du heute Abend da? Dann schauen wir uns das mal an.

73 Ralf

**Comment by dh3wr** [comment]
Eine Interessante Stelle: http://www.bbk.bund.de/DE/AufgabenundAusstattung/Krisenmanagement/WarnungderBevoelkerung/Warnmultiplikatoren/Warnmultiplikatoren_node.html

**Comment by dh3wr** [comment]
Als Datenquelle könnte man http://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json nehmen. Jedenfalls benutzt das die Warnungs-Anzeige des BKK.

**Comment by dh3wr** [comment]
Das BKK hat mittlerweile geantwortet und prüft die Sache. Wir haben schon Beispieldateien bekommen. Die Implementation wird aber wohl eher als eigenständiges Programm realisiert werden, welches auf dei REST API zugreift.

**Comment by rtausend** [comment]
Hallo Ralf, kannst Du die Beispieldaten vielleicht weiterleiten? :) Danke

**Comment by dh3wr** [comment]
Hallo Robert, habe dir etwas weitergeleitet. Wenn du magst, kann du gerne die Software von CAP nach REST entwickelt.
Habe gerade mit dem Ministerium telefoniert. Die prüfen die Sache noch juristisch und melden sich dann bei mir.
