### ISSUE TITLE
Removing Zero Width White Spaces in REST content

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#163]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Web/commit/201b655e3618003f5868f23f2957c11c3d64f618

Das sollte auch zur Sicherheit im Core geschehen.

**Comment by Taronyu** [comment]
Ganz so einfach ist das im Core vermutlich nicht. Wenn es keinen Handler gibt, mit dem man den REST String vorab bearbeiten kann, muss das bei jeder Deserialisierung einzeln gemacht werden. Das heißt jeder Methodenparameter und ggf. jedes eingehende JSON Objekt bearbeiten. Das wäre dann definitiv nicht mit mal eben getan

**Comment by dh3wr** [comment]
Copy&Paste wahrscheinlich. Aber ok, dann fangen wir das im Web ab, und bei anderen REST-Quellen wird man wohl besser auf die gesendeten Zeichzen aufpassen.

**Comment by Taronyu** [comment]
Eventuell im refactoring branch gefixt
