### ISSUE TITLE
Gültige Zeichen für Passwort in 401 Fehlermeldung melden

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#164]
Hier bestand offensichtlich ein SonderzeichenProblem im Passwort. Leider ist die 401 Meldung generisch.
Daher bitte gültige Zeichen für Passwort in 401 Fehlermeldung melden.

![grafik](https://user-images.githubusercontent.com/16710361/39800926-cb876564-5369-11e8-8d92-9641865c8a94.png)

**Comment by dh3wr** [comment]
Wobei https://httpstatuses.com/401 ja auth ist und nicht "Zeichenfehler"... ?

**Comment by Taronyu** [comment]
Hatten wir nicht mal ein Problem damit, dass nach der Änderung des Passworts der API-Zugriff nicht mehr funktioniert, weil ja das Passwort nicht mehr stimmt?

**Comment by dh3wr** [comment]
Ja, das wurde aber meines Erachtens behoben. Hat @MarvinMenzerath dazu Wissen?

**Comment by MarvinMenzerath** [comment]
Mittlerweile werden nur noch A-Z, a-z und 0-9 als Zeichen akzeptiert. Sollte es da einen Fehler geben, werden keine Daten an den Core gesendet.
Sobald der Core das neue Passwort akzeptiert hat, wird intern auf die neuen Zugangsdaten gewechselt.

**Comment by Taronyu** [comment]
Ok, hab das im letzten Commit auch im Core gefiltert, ist allerdings noch kein neues Release draußen. Ich gucke mir erst noch ein paar andere Tickets an.

**Comment by dh3wr** [comment]
Danke @Taronyu
