### ISSUE TITLE
Keine IP bei nicht-verbundenen Knoten in Doku vermerken

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#17]
Bei der Ausgabe aller Knoten wird bei nicht-verbundenen Knoten keine IP und kein Port im JSON angegeben (siehe DecentralizedAmateurPagingNetwork/Web#6).
Das sollte in der Dokumentation der API vermerkt werden.

**Comment by dh3wr** [comment]
Updated in Wiki
