### ISSUE TITLE
Linked website is down

### ISSUE THREAD

**Issue by programmin1** [DecentralizedAmateurPagingNetwork/Core#172]
The linked [website](https://www.afu.rwth-aachen.de/projekte/funkruf-pager-pocsag/funkrufmaster-2-0-dapnet) is down. Is this related to the redesign mentioned in the readme?

**Comment by dh3wr** [comment]
Hi, not the complete webside, but this page is down. I will update the readme, although the redesign will render this software useless. Thanks for the info.

**Comment by dh3wr** [comment]
Where did you find this link? In this repo it's not present.

**Comment by dh47** [comment]
It's located in the repo discription.
