### ISSUE TITLE
Tausch des Verbindungsaufbaus von Core und Raspager/SDR-Pager

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#18]
Um auf Seite des Raspagers/SDR-Pagers keine eingehenden Ports zu brauchen wäre es sehr schön, wenn sich der Sender beim Core auf einem festen Port anmelden kann, statt dass der Core den Sender kontaktiert. Dazu müsste man eine modifizierte Version des Raspagers /SDR-Pagers veröffentlichen und entsprechend einen 2 neue Sender-Typen definieren. Die C9000 bleiben weiterhin mit Verbindungsaufbau vom Core aus, da die das nicht anders können.

**Comment by rtausend** [comment]
Da wäre ich auch SEHR dafür da man dann auch von dynamischen IP's in der Lage wäre eine Verbindung aufzubauen. Bräuchte man dafür dann aber nicht eine art Authentifizierung? Nicht an jedem Standort ist eine Hamnetanbindung vorhanden, Internet dafür aber fast immer

**Comment by dh3wr** [comment]
Das wäre nun echt eine sehr gute Verbesserung, gerade bei Sendern, die keine eingehenden Portweiterleitungen können, wie z.B. LTE Hotspots. Die Auth. müsste man tatsächlich machen. Vielleicht gibt es da eine Möglichkeit mit private und public key? Statt Klartextpasswort?

**Comment by Taronyu** [comment]
Technisch geht das sicher schon, müsste man sich mal ansehen, ob Java da etwas mitbringt. Ich habe eh nicht verstanden, warum das nicht von Anfang an andersherum gemacht wurde. Es macht schließlich viel mehr Sinn, sich mit einem Masterserver zu verbinden als umgekehrt. Für die C9000 kann man sicherlich auch was basteln.

**Comment by dh3wr** [comment]
Der historische Grund war, dass zu AX.25 Zeiten das Konzept halt war, dass der Master seine Slaves sowohl connected als auch entsprechend konfiguriert (Zeitkorrektur und Zeitschlitze). Unter AX.25 war eine NAT-Freie End2End Kommunikation immer gegeben. In der jetzigen LTE-Router-TCP-Welt ist das nicht mehr der Fall. Daher der Vorschlag:

- [ ] Festlegen eines Ports für diese Verbindungen von außen (Ralf)
- [ ] Öffnen des Ports in der RWTH Firewall und entsprechendes weiterleiten auf den Rechner bei uns (Ralf)
- [ ] Implementierung eines TCP Servers im Core auf dem entsprechenden Port (!Ralf)
- [ ] Anpassung der Datenstruktur des Cores: Hinzufügen eines Sender-Typs "SDRPager-Aktiv", "C9000-Aktiv" und "Raspager1-Aktiv"
- [ ] Diese Sender-Typen haben dann keine IP und Port mehr als Eigenschaften, dafür aber ein Auth-Token
- [ ] Beim Connect des Senders zum Master wird das Auth-Token als Identifikation benutzt und entsprechend der im Core eingetragene Sender ausgewählt
- [ ] Ablehnung der Verbindung, wenn schon ein Sender mit diesem Auth-Token verbunden ist (keine Doppelverbindungen)
- [ ] Kommunikationsprotokoll auf der TCP-Verbindung weiterhin wie gehabt; Nur am Anfang sendet der Sender als ersten String sein AuthToken an den Core, der dann entsprechend weitermacht oder auch nicht
- [ ] Update der Web-Oberfläche zur Eingabe / Automatischen Generierung des Tokens, Wegfall der IP/Port bei den "*-Aktiv" Sendertypen

**Comment by dh3wr** [comment]
Ich habe mal die Liste an die Ergebnisse von gestern angepasst.

**Comment by Taronyu** [comment]
Update von gestern: Im experimental Branch ist eine erste lauffähige Version des neuen DAPNET Core zu finden. Da ist noch etwas Feinschliff erforderlich und wir müssten das auch noch weiter testen. Sobald das zuverlässig genug funktioniert, werde ich die Änderungen in den master Branch mergen und ein neues Release bauen.

Der Proxy-Server für die alten Geräte ist auch schon funktionsfähig und ist unter [raspager-proxy](https://github.com/rwth-afu/raspager-proxy) zu finden. Der Service ist zwar primär für die C9000 Raspager gedacht, funktioniert aber auch mit den anderen noch nicht umgestellten Versionen. Die wollen wir aber sauber umbauen, bei den C9000 geht das halt nicht.

Es ist eventuell auch sinnvoll, das Protokoll zu überarbeiten. Der Proxy kann so erweitert werden, dass er mit den C9000 das alte Protokoll spricht und mit dem DAPNET Core das neue Protokoll (JSON oder was anderes). So richtig hübsch ist das aktuelle Protokoll nämlich nicht.

Die Anpassung der GUI steht noch aus, das muss vor Release auch noch erfolgen.

**Comment by MarvinMenzerath** [comment]
> Die Anpassung der GUI steht noch aus, das muss vor Release auch noch erfolgen.

Ist soweit erledigt (inkl. der Änderungen aus #47), kann jetzt ausgiebig getestet werden

**Comment by Taronyu** [comment]
Im aktuellen Commit im experimental Branch ist nun die Authentifizierung via Transmittername und Authkey implementiert. Der Proxy ist auch entsprechend angepasst.

**Comment by Taronyu** [comment]
Der getauschte Verbindungsmodus ist nun auch im master Branch.

**Comment by dh3wr** [comment]
Da muss nun noch der Rustpager nachgezogen werden? Authkey gibt es jetzt ja nicht mehr so wie ursprünglich. Was ist mit dem Umbau der state.json? Die hat doch auch eine neue Struktur,oder?

**Comment by Taronyu** [comment]
Ja, der neue Login-String sieht momentan so aus "[Typ Version Name Key]". Also vor dem Key ist noch der Name hinzugekommen.

Hast du vielleicht eine alte State.json für mich? Ich habe leider nur eine neue Version von meinem Testlauf nach der Anpassung. Man muss da idealerweise ein Konverterskript bauen, dass die Datei auf das neue Format umbauen kann.

**Comment by Taronyu** [comment]
Ich mache dann hier mal zu, das ist ja soweit im Core umgebaut und mittlerweile auch im master Branch.
