### ISSUE TITLE
Pull Request #22: API URI

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#25]
Frage:
src/org/dapnet/core/rest/RestManager.java
 
 public void startServer() {
         try {
             ResourceConfig rc = new ResourceConfig().packages("org/dapnet/core/rest");
-            URI endpoint = new URI("http://localhost:"+Settings.getRestSettings().getPort()+"/");
+            URI endpoint = new URI("http://localhost:" + Settings.getRestSettings().getPort() + "/");
             server = JdkHttpServerFactory.createHttpServer(endpoint, rc);
             logger.info("RestApi successfully started");
         } catch (Exception e) {

Ist "localhost" hier richtig? Der Server wird doch nie von Localhost angesprochen, es sei denn, die Web-Oberfläche wird vom gleichen Rechner aufgerufen, auf dem auch der Core läuft.

**Comment by dh3wr** [comment]
Daniel? Any thoughts?

**Comment by DanielSialkowski** [comment]
Der uri endpoint gibt den Ort an an dem die REST Schnittstelle angesprochen werden kann und das ist der gleiche Server auf dem auch der DAPNET Core läuft...
