### ISSUE TITLE
Überlegen ob Probleme bei Daten durch gleichzeitigen Zugriff aus mehreren Threads

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#3]
Verwendete ArrayList ist nicht threadsicher, jedoch laufen alle Schreibzugriffe seriell über das Cluster...

**Comment by Taronyu** [comment]
Ich gucke mir das generell mal an.

**Comment by Taronyu** [comment]
Ich habe diese Arraylisten mal gegen ConcurrentMaps getauscht, da spart man sich jetzt auch die sequentielle Suchen.
