### ISSUE TITLE
XOS Sender werden nicht akzeptiert, wenn sie langsam antworten

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#32]
Beispiel DB0RTV
Der Sender meldet:
root@db0sda:/opt/DAPNET_CORE# telnet localhost 19996
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
RPC/XOS 2.2.0pre32
****** Funkrufsender - DB0RTV - Rheine - JO32RG ******
************ Funkrufe bitte ▒ber  DB0DY-11 ***********
************ oder  www.db0rtv.de  absenden ***********

=>^]
telnet> quit
Connection closed.

Der DAPNET-Core sagt:

2016-11-07 15:42:01,597 WARN org.dapnet.core.transmission.TransmitterDevice [Thread-16] db0rtv is offline now and throws Exception: Connection error: WRONG SID:  Expected SID to start with */XOS

Die Erkennung von */XOS scheint nicht zu gehen

**Comment by dh3wr** [comment]
Es liegt wohl daran, dass die Begrüßungszeile erst nach ca. 2 Sek. kommt und damit Readline einen leeren String liefert.

**Comment by dh3wr** [comment]
Wie machen wir hier jetzt weiter? Es scheint ja an der langsamen Antwort zu liegen, die dann in eine empty line resultieren. Kann man dem readline ein Timeout geben?

**Comment by MarvinMenzerath** [comment]
Laut der `BufferedReader`-Dokumentation unter https://docs.oracle.com/javase/7/docs/api/java/io/BufferedReader.html kann man durch die `ready()`-Methode abfragen, ob man mittels `readLine()` Daten lesen kann.
Vielleicht sollten wir statt direkt mit
```java
String msg = fromServer.readLine();
```
zu lesen, dem Sender ein paar Sekunden Zeit geben die Begrüßung zu senden und erst wenn `fromServer.ready()` `true` ergibt die Zeile einlesen.
Hier müsste man dann vielleicht ein eigenes Timeout einbauen oder den Wert aus der Klasse `TransmissionSettings` (s.u.) verwenden...

---

zum Timeout: in der Klasse `TransmissionSettings` wird in Zeile 52 ein Socket Timeout von 20s mittels
```java
private int connectionTimeout = 20000;

public int getConnectionTimeout() {
    return connectionTimeout;
}
```
gesetzt.
Dieses Timeout wird dann in der `connect()`-Methode der `Raspager`-Klasse verwendet:
```java
socket.connect(new InetSocketAddress(address.getIpAddress().getHostAddress(),
    address.getPort()), settings.getConnectionTimeout());
```

**Comment by dh3wr** [comment]
ok, ist das schon implementiert? Wenn nicht, dann bitte dies tun und dann können wir das testen.

**Comment by dh3wr** [comment]
Geht jetzt , danke Marvin
