### ISSUE TITLE
Pager Nummern fehlt die führende Null

### ISSUE THREAD

**Issue by phl0** [DecentralizedAmateurPagingNetwork/Core#38]
Ich habe hier einen Skyper mit der ID 0101531. Im DAPNET Core sowie in den Logs taucht allerdings immer "nur" "101531" als ID auf. Es wäre sinnvoll, hier die Strings mit führender Null auszugeben.

![bildschirmfoto vom 2016-12-07 13-39-19](https://cloud.githubusercontent.com/assets/7112907/20968066/ce6a9492-bc82-11e6-9979-9c81f0cb03c8.png)

**Comment by dh3wr** [comment]
Warum? Ist es so nicht eindeutig?

**Comment by phl0** [comment]
Mich hat es eine Zeit lang verwirrt ...

**Comment by dh3wr** [comment]
Vielleicht kann sich Marvin der Sache kurz annehmen?

**Comment by phl0** [comment]
Ich versuche es auch gerade selbst. Allerdings ist das mehr try+error :D

**Comment by phl0** [comment]
Bin grad auch gar nicht sicher, ob das Ding nur Web oder auch Core betrifft.

**Comment by dh3wr** [comment]
Also der Core sollte damit keine Probleme haben, da die Nummer ja sowieso bitweise encodiert wird. Es wäre also nur Kosmetik im Frontend.

**Comment by MarvinMenzerath** [comment]
Soll ich mir das mal anschauen?

**Comment by phl0** [comment]
@dh3wr hat mir bereits was zum Testen geschickt. Ich werde das nachher mal ausprobieren.

**Comment by dh3wr** [comment]
Any news?

**Comment by phl0** [comment]
Von meiner Seite noch nicht. Ich hatte bisher zu wenig Zeit dazu, mir das genauer anzusehen.

**Comment by phl0** [comment]
Ich mache gerade meine ersten Schrite mit JSON und JS. Hab eine Stelle im apiclient.js (Zeile 186) gefunden. Dort wird die Pager Nummer aus dem JSON Datenstrom extrahiert und eingesetzt. Bin ich da an der richtigen Stelle? :-)

**Comment by Taronyu** [comment]
In der Klasse Pager.java ist die Pagernummer ein int, da gibt es also keine führende 0. Man kann bei der Ausgabe den String aber so formatieren, dass der mit führenden Nullen gepadded wird. Das müsste aber im Frontend (Web) gelöst werden und nicht im Core.

**Comment by phl0** [comment]
Deswegen hatte ich ja im Code des Webif geschaut. Bin nur nicht wirklich fit in jQuery und json... :-(

**Comment by MarvinMenzerath** [comment]
Der Konsistenz zuliebe würde ich vorschlagen, dass die Änderung der Anzeige in Core und Web erfolgen sollten, damit es keine Unterschiede zwischen z.B. der Anzeige im Browser und den Logs vom Core gibt.
Bleibt für mich die Frage: brauchen wir diese "Kosmetik", oder reicht ein Hinweis, dass führende Nullen nicht mit angegeben werden sollen?

**Comment by phl0** [comment]
Angeben kann man sie ja jetzt auch schon. Sie werden eben einfach beim
Eintragen nicht beachtet. Die Idee, dass im Core und Web konsistent zu
haben, finde ich gut. Ich probiere mich mal am Code vom Core.

**Comment by Taronyu** [comment]
Im Core wird die Nummer als integer gespeichert, da gibt es keine führende Null. Beim tostring habe ich das schon angepasst, dass mit führenden Nullen auf 7 Zeichen gepaddet wird (experimental Branch).

**Comment by MarvinMenzerath** [comment]
Im Web-Interface ist das Padding mittlerweile implementiert; wenn im Core auch alles läuft, dann können wir hier zu machen.

**Comment by phl0** [comment]
Sieht soweit gut aus. Hier klappt alles. 

![bildschirmfoto vom 2017-02-03 11-32-56](https://cloud.githubusercontent.com/assets/7112907/22588093/aa96d800-ea04-11e6-8daa-a0a2b42b668d.png)

![bildschirmfoto vom 2017-02-03 11-33-10](https://cloud.githubusercontent.com/assets/7112907/22588099/adf37864-ea04-11e6-9a40-ea88390ae215.png)
