### ISSUE TITLE
DAPNET Knoten im APRS Netz darstellen

### ISSUE THREAD

**Issue by phl0** [DecentralizedAmateurPagingNetwork/Core#43]
Hallo liebe OMs, 

mir kam gerade die Idee, den DAPNET Master an das APRS-IS anzubinden und DAPNET Knoten dorthin zu übermitteln. Würde natürlich nur für solche Knoten Sinn machen, die auch online sind.
Dann wären sie z.B. auf aprs.fi sichtbar.
Was haltet ihr von der Idee?

**Comment by dh3wr** [comment]
Hallo Florian,
das ist eine hervoragende Idee. Es würde jeweils der "Besitzer-Core" die Baken generieren, denke ich. Dann hat man keine Doppel-Meldungen und die Aufgaben sind auch im verteilten Netz klar definiert. Kennst du dich mit Java aus und würdest das selbst implementieren?

Grüße
Ralf

**Comment by dh3wr** [comment]
Als Kommentar-Text könnte man auch die freigegebenen Zeitschlitze angeben und ebenfalls die "APRS-Reichweite" http://www.aprs-dl.de/?APRS_Detailwissen:PHG_Parameter . Es fehlt bei unserem Datenmodell leider die Höhe. Entweder, wir bauen die noch ein oder parsen sie wo es möglich ist aus der HamnetDB.

**Comment by phl0** [comment]
Ja genau. Ich habe auch an eine Ausgabe der aktiven Zeitschlitze gedacht... Muss ich mich wohl doch noch in die Java Sourcen einarbeiten :-)

**Comment by dh3wr** [comment]
Die PHGParameter können bald auch berechnet werden, siehe: https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/47

**Comment by dh3wr** [comment]
@phl0 Any update?

**Comment by dh3wr** [comment]
Die Frage die sich stellt: Wollen wir das auch im Core haben oder lieber ein ext. Skript, was über REST die Nodes und Sender-Locations ausließt und dann in APRS verpackt?

**Comment by dh3wr** [comment]
Ausgelagert:
https://github.com/DecentralizedAmateurPagingNetwork/DAPNETAPRS
