### ISSUE TITLE
"Nicht-Admins" können im Webinterface...

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Core#45]
1) ...Skyper (also Rufzeichen) anlegen
     -> Sollte dahingehend geändert werden, dass nur der eigene Pager bearbeitet werden kann und die Neuerstellung entfällt

2) ...Sender anlegen
     -> Dürfte mit der Verbindungsrichtungsumstellung erledigt sein, allerdings muss die Schlüsselgenerierung gesperrt werden

3) ...Sendergruppen anlegen
     -> muss gesperrt werden!

4) ...Nutzer ohne Admin-Rechte anlegen
     -> muss dringend gesperrt werden, um einem Missbrauch des Systems vorzubeugen!

Zu prüfen ist noch, ob diese Lücken über die Curl-Schnittstelle ebenfalls bestehen.

**Comment by Taronyu** [comment]
Da das Problem vermutlich in den REST-Handlern des Cores zu suchen ist, dürfte auch die curl-Schnittstelle betroffen sein.

**Comment by DanielSialkowski** [comment]
Wie @Taronyu bereits erwähnt hat ist die REST Schnittstelle die einzige zum Core, sodass dieser unabhängig davon wie dieser angesprochen wird (curl, Webinterface, etc.) immer das gleiche Verhalten zeigt.
Die Rechte wurden ursprünglich sehr locker gesetzt. Sie lassen sich sehr einfach für jeden REST Funktion setzten in dem bei der Autorisierungsüberprüfung der letzte Parameter angepasst wird:
`checkAuthorization(RestSecurity.SecurityLevel.OWNER_ONLY);`
Unterstützt wird zur Zeit:
`public enum SecurityLevel {
		ADMIN_ONLY, OWNER_ONLY, USER_ONLY, EVERYBODY
	}`
Ich würde vorschlagen, die ganze Thematik zunächst zu diskutieren. Die ursprüngliche Idee ist, dass jeder Nutzer (ohne Adminrechte) seinen eigenen Sender hinzufügen kann. Zum Aussenden einer Nachricht kann er dann auch seine eigene Sendergruppe anlegen. Wenn man den Prozess mehr kontrollieren möchte, dann kann man die Funktionen natürlich auf Admins einschränken...

**Comment by dj7lc** [comment]
Alles klar. Ich hatte im Quellcode die entsprechende Stelle gelesen, war mir aber nicht sicher, ob das der einzige Punkt ist, wo Rechte festgelegt werden.

Meiner Ansicht nach sollte das Anlegen von Sendern für User aus folgenden Gründen gesperrt werden:
1. Irgendwann wird das passieren, was beim DMR-Digitalfunknetz schon passiert ist: Die Eintragungen werden nicht sauber gemacht, wir haben dann einen Haufen "Testsender", die im Koordinatenursprung stehen, oder am verkehrten Standort.
2. Zeitschlitze: Ein neuer Sender kann es erforderlich machen, dass in einer Region alle Zeitschlitze umstrukturiert werden müssen, um Überlappungen zu vermeiden. Das sollte dann von einem Admin gemacht werden, der die lokale geographischen Lage kennt und die Reichweiten richtig einschätzen kann. Bei gegenwärtig 40 Sendern kann man noch die Übersicht behalten und die Eintragungen machen. Wenn das Netz aber so weiterwächst, ist das bei 200 Sendern nicht mehr möglich. Wenn nur Admins Eintragungen machen können, sind sie über die Neuerungen sofort informiert und können die Vergabe entsprechend anpassen.
3. Missbrauch, siehe "Nutzer anlegen" unten.

Dasselbe gilt für Sendergruppen: Wenn beliebig viele Gruppen zugelassen werden, blickt irgendwann keiner mehr durch, welcher Sender über welche Gruppen zu erreichen ist. Der Vorschlag einer automatisierten Zuteilung ist durchaus interessant https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/44

Zuletzt das Thema "Nutzer anlegen": Was jeder mit seinem Account macht und wem er die Zugangsaten gibt ist letztlich dessen "eigenes Bier". Irgendwann wird es aber passieren, dass unter Phantasierufzeichen Accounts für Kumpel erstellt werden, "damit die auch mal was schreiben können". Leztenendes ist das aber Funkbetrieb ohne Lizenz. Sollte sich, warum auch immer, die BNetzA dafür interessieren, hat zunächst Ralf als Betreiber von hampager.de den Ärger damit.
Dies ist nicht so weit hergeholt, denn für die Amateur-Digitalfunk-Registrierung laufen täglich haufenweise Fake-Anträge auf (Betriebsfunk, Kurierdienste, etc). Es gab auch schon den Fall, dass ein Fake-Rufzeichen tatsächlich vergeben war und der rechtmäßige Inhaber sich mit einer Strafanzeige auseinandersetzen musste, weil der Faker in seinem Namen über Funk die Sau rausgelassen hatte. Dies müssen wir bei Dapnet unbedingt vermeiden.

**Comment by dj7lc** [comment]
Bevor wir Dapnet an die ganz große Glocke hängen, sollten wir das Thema "Berechtigungen" geklärt haben, daher schiebe ich das Thema noch mal an.

**Comment by Taronyu** [comment]
Das Anlegen von Usern, Sendern, Sendergruppen und Rufzeichen ist im `master` Branch nun auf Admins beschränkt. Owner können ihre Daten noch ändern und löschen.

**Comment by dj7lc** [comment]
Wunderbar, danke!

**Comment by Taronyu** [comment]
Was wir vielleicht noch einmal überlegen sollten: Aktuell ist es so, dass der Owner seine Ressource löschen kann. Sollen wir das für bestimmte Ressourcen auch noch auf Admins beschränken?

**Comment by dj7lc** [comment]
Wenn jemand seine eigene Ressource löschen will, sollten wir ihn nicht aufhalten :-)
Bei den wichtigen Sendergruppen und Rubriken ist sowieso admin als Besitzer eingetragen, von daher kann eigentlich nichts anbrennen.

**Comment by Taronyu** [comment]
Gut, dann mache ich hier jetzt erst einmal zu.
