### ISSUE TITLE
Update eines Senders trennt die Verbindung

### ISSUE THREAD

**Issue by Taronyu** [DecentralizedAmateurPagingNetwork/Core#46]
Aktuell wird in RpcListener::putTransmitter die bestehende Verbindung getrennt. Durch die Umkehrung des Verbindungsaufbaus baut der Core nun keine neue Verbindung mehr auf, sondern der Client müsste sich erneut verbinden. Soll das so bleiben?

**Comment by dh3wr** [comment]
Das wäre ok. Die Sender sollen bei Abbruch der Verbindung automatisch reconnecten, würde ich sagen

**Comment by Taronyu** [comment]
Okay, dann lass ich das erst mal so und wir müssen das im Proxy bzw. im Sender abfangen.
