### ISSUE TITLE
Erweiterung: Eigenschaften von Sendern

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#47]
Nachdem in https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/33 schon beschrieben ist, wie die Readonlychkeit bei den Sender-Werten ist, kommt mir die Idee, ob man nicht direkt noch ein paar Werte direkt mehr einbaut.

Es fällt mir spontan ein:
- Höhe der Antenne über Grund in Metern
- Geplante Nutzung: Wide-Range-Sender oder privater 10 mW Raspager
- Art der Antenne (Omni oder Richtantenne)
- Bei Richtantenne Hauptstrahlrichtung
- (Antennengewinn - Kabelverluste)

Wenn wir nun eh von Hand nach der Umstellung die State.json anpassen müssen, könnte man das direkt mit übernehmen.

**Comment by Taronyu** [comment]
Das klingt sinnvoll. Ich baue das mal in den experimental Branch ein.

**Comment by dh3wr** [comment]
Bau mal ein. Ich denke, das reicht erstmal. Hier die gültigen Wertebereiche für den Validator

- Höhe der Antenne über Grund in Metern [0 bis 1000] Einheit m, Type float
- Geplante Nutzung: Wide-Range-Sender oder privater Sender ["Widerange" | "Personal"]
- Art der Antenne (Omni oder Richtantenne) ["omni" | "directional"]
- Bei Richtantenne Hauptstrahlrichtung [0 bis 359]
- (Antennengewinn - Kabelverluste) in dBi [-50 bis + 80] Einheit dBi, Type float

**Comment by dj7lc** [comment]
> Höhe der Antenne über Grund in Metern [0 bis 1000] Einheit m, Type float

Da fallen mir ohne groß nachzudenken schon ein paar Relaisstandorte ein, die mit der Zahl nicht auskommen. Eine Null mehr sollte es schon sein!

**Comment by dh3wr** [comment]
Mehr als 1000 m **über Grund**?

**Comment by dj7lc** [comment]
Akute Leseschwäche :-) Ich hatte angenommen, es ginge um Normalnull.
1000 Meter sollten ausreichen, selbst wenn die Scheichs beschließen, auf dem Burj Khalifa einen Sender zu installieren (der Standort wäre 140km Radiohorizont und 61000 km² Abdeckung schon ganz passabel).
Ich ziehe meine vorschnelle Kritik zurück.

**Comment by dh3wr** [comment]
Das sagt uns aber, dass wir das ins Webinterface **DICK** hinschreiben müssen, sonst kommen wieder Rückmeldungen wegen zurückgewiesenen Eingaben...

**Comment by dj7lc** [comment]
So isses!

**Comment by Taronyu** [comment]
Ich habe die Änderungen im experimental Branch eingepflegt. Wenn das soweit in Ordnung ist, können wir das hier zu machen.

**Comment by dh3wr** [comment]
Man könnte die Telemetrie-Daten aus https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/47 hier auch einbauen. Aber vielleicht später
