### ISSUE TITLE
Zu lange Pager-Nummer liefert "API nicht erreichbar"

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#48]
Wenn man eine zu lange Pager-Nummer eingibt, kommt statt einer aussagekräftigen Fehlermeldung ein "API nicht erreichbar".--> Error Handling

**Comment by Taronyu** [comment]
Wie lang darf die Nummer denn sein? Ich nehme mal an, die Meldung kam auch aus der Web GUI? Eventuell hat der Validator zugeschlagen und das wurde nicht sauber weitergeleitet.

**Comment by dh3wr** [comment]
> Eventuell hat der Validator zugeschlagen und das wurde nicht sauber weitergeleitet.
Danach sieht es aus. Begrenzung bei max. 7 Zeichen.

**Comment by Taronyu** [comment]
In Call.java ist der Maximalwert für die Nummer aktuell auf 2097151 begrenzt, das müssten 20 Bit sein.

**Comment by phl0** [comment]
Ist das nicht zu klein? Müsste der Bereich nicht bis 9999999 gehen?

**Comment by dh3wr** [comment]
Laut http://www.uni-stuttgart.de/akafunk/aktivitaet/basics/pocsag-protokoll.html ist die pager Adresse 21 Bit lang.

**Comment by Taronyu** [comment]
Ich habe da auch 21 Bit im Kopf.

**Comment by phl0** [comment]
Dann passt 2097151 ja auch :-)
Danke für den Link auf das Protokoll.

**Comment by Taronyu** [comment]
Ich habe mal eine zusätzliche Message für den Validator konfiguriert. Kann aber nicht sagen, ob das was nützt. Vermutlich muss das trotzdem in der GUI behandelt werden.

**Comment by MarvinMenzerath** [comment]
> Vermutlich muss das trotzdem in der GUI behandelt werden.

Insofern die API eine Constraint Violation zurückgibt (was ja jetzt passiert), wird diese ausgegeben. Anderenfalls fliegt die generische Meldung von oben.
(@dh3wr bzgl. https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/40)
