### ISSUE TITLE
Erweiterung Core um UUID als AuthKey dopplungsfrei zu erzeugen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#50]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/38

**Comment by Taronyu** [comment]
Da wollte ich eigentlich schon mit angefangen haben.

**Comment by Taronyu** [comment]
Okay, wir sollten vielleicht noch einmal über die Authentifizierung nachdenken... (siehe https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/38)

**Comment by Taronyu** [comment]
Ich habe den Auth key Generator wieder entfernt, da die Authentifizierung jetzt über Transmittername und Passwort läuft.
