### ISSUE TITLE
Einheitliche Rufzeichen

### ISSUE THREAD

**Issue by 7h0ma5** [DecentralizedAmateurPagingNetwork/Core#53]
Damit die Rufzeichen der Sender ein einheitliches Format haben, würde ich vorschlagen, alle Rufzeichen, die über das REST-API übergeben werden, automatisch in Großbuchstaben umzuwandeln und auch nur in Großbuchstaben abzuspeichern. Alternativ könnte man natürlich auch nur Kleinbuchstaben verwenden.

**Comment by Taronyu** [comment]
Im Prinzip eine gute Idee, leider entzieht sich das durch die Art wie Java Klassen serialisiert meiner Kontrolle. Die Serialisierung arbeitet direkt auf den Klassenattributen, ich kann also nicht einfach in die Getter/Setter eingreifen und das dort regeln. Die Daten müssten schon im JSON korrekt sein. Abgesehen davon müsste man auch ein Skript schreiben, das die State.json konvertiert, sonst geht auch da wieder ein Teil der Daten verloren.

**Comment by Taronyu** [comment]
Ist im aktuelle commit drinnen. Die Namen sind (hoffentlich) nun alle in lower case angegeben. Das state-convert Skript ist auch angepasst.

**Comment by dj7lc** [comment]
Danke für die Implementierung, allerdings erscheint mir Convert.ToUpper eher angebracht, denn Amateurfunkrufzeichen werden praktisch überall im Upper Case geschrieben.

**Comment by dh3wr** [comment]
Das ist aber für Eingeben eher umständlich, oder? Wenn man immer shift drücken muss?

**Comment by dj7lc** [comment]
Meinst Du bei der Rufauslösung? Das stimmt natürlich. Ließe es sich einrichten, dass die Groß- und Kleinschreibung einfach ignoriert wird? Dann hätten wir damit nie mehr Probleme.

**Comment by dh3wr** [comment]
Und beim Usernamen beim Einloggen

**Comment by 7h0ma5** [comment]
Es geht darum, dass egal was ein Benutzer eingibt, das Rufzeichen immer in ein einheitliches Format umgewandelt wird, für den Benutzer ändert sich also nichts.

**Comment by dj7lc** [comment]
Der Username hat nichts mit dem Rufzeichen zu tun, das für einen Pagerruf ausgewählt wird. Ich denke dabei an externe Systeme (Packet Radio, DMR, etc.), die über Curl auch Pagerrufe auslösen können und alle mit Großbuchstaben arbeiten. Damit schließen wir eine mögliche Fehlerquelle aus.
