### ISSUE TITLE
Sonderzeichen in UTF8 machen Probleme mit Validator

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#54]
````21:30:19.257 [main] ERROR org.dapnet.core.cluster.ClusterManager - Error validating State.json: callSigns[do1kmt].pagers[0].name size must be between 3 and 20````

````
    "do1kmt": {
      "name": "do1kmt",
      "description": "Kevin",
      "pagers": [
        {
          "number": 68705,
          "name": "SkyperGrÃ^ÃÂ^ÃÃ^ÂÂ^ÃÃ^ÃÂ^ÂÃ^ÂÂ¼n"
        }
      ],
      "ownerNames": [
        "do1kmt"
      ]
````
Das gleiche scheint auch bei Rufen zu geschehen. Wahrscheinlich ein generelles Problem.

**Comment by Taronyu** [comment]
In der State.json, die du mir mal geschickt hattest, ist das leider auch schon kaputt:  "SkyperGrÃ¼n". Ich habe mit verschiedenen Encodings herumgespielt, kann aber nicht feststellen, welches das ursprünglich mal war. Lesbar habe ich das jedenfalls nicht mehr machen können. Mir ist allerdings aufgefallen, dass die State.json in ANSI gespeichert wird, zumindest auf meiner Windows Maschine. Ich habe das mal auf UTF-8 umgestellt, eventuell war das deswegen kaputt gegangen. Leider sind die kaputten Einträge weiterhin kaputt, die müsste man mit richtigem Encoding reparieren.

**Comment by dh3wr** [comment]
Ging in der aktuellen Version jetzt ohne Probleme. Sowohl der Convert als auch das Einlesen im Core.

**Comment by Taronyu** [comment]
Schön :-)
