### ISSUE TITLE
API Ausgabe in altes Format überführen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#55]
Nur der Transparenz wegen hier das Issue zur API Ausgabe, die wieder die strukturierte Form von vorher haben soll.

**Comment by Taronyu** [comment]
Ich habe das nun repariert. Das gilt allerdings nur für das REST API, in der State.json wird das weiterhin anders gemacht. Eigentlich wollte ich in die Gson Serialisierung eingreifen, das hat sich aber als komplizierter als gedacht herausgestellt. Für die State.json haben wir aber das Konverterskript.
