### ISSUE TITLE
Initiale Cluster-Verbindung geht nicht

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#56]
Ein Test mit der aktuellen Version liefert known node Fehlermeldung bei der Authentifizierung. Vielleicht ist mit der neuen Datenstruktur was kaputt gegangen?

**Comment by dh3wr** [comment]
Hier noch ein paar Logs:
db0sda als Master mit neu angelegtem Node "db0wa"
````
16:14:31.128 [Thread-4] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0sda|1] (2) [db0sda, db0wa]
16:14:31.129 [Thread-4] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of db0wa from SUSPENDED to ONLINE
16:14:31.129 [Thread-4] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
16:14:31.144 [Thread-4] INFO  org.dapnet.core.model.State - Successfully wrote state to file
````

Log von db0wa
````
16:14:31.952 [Thread-2] INFO  org.dapnet.core.transmission.Server - Server started on port: 43434
16:14:35.769 [INT-1,DAPNET1.1.0.0,db0wa] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda failed: Unknown node
16:14:36.613 [INT-1,DAPNET1.1.0.0,db0wa] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda failed: Unknown node
16:14:37.114 [INT-1,DAPNET1.1.0.0,db0wa] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda failed: Unknown node
````

Wo es herkommt: https://github.com/DecentralizedAmateurPagingNetwork/Core/blob/master/src/main/java/org/dapnet/core/cluster/ClusterAuthentication.java
````
public boolean authenticate(AuthToken token, Message msg) {
		Address sender = msg.getSrc();
		/*
		 * IpAddress address = sender != null ? (IpAddress) auth.down(new
		 * Event(Event.GET_PHYSICAL_ADDRESS, sender)) : null;
		 */
		if (clusterManager == null) {
			logger.error("Authentication has no reference to ClusterManager");
			return false;
		}

		Node node = clusterManager.getState().getNodes().get(sender.toString());
		if (node == null) {
			logger.warn("Authentication of Node " + sender.toString() + " failed: Unknown node");
			return false;
}
````

**Comment by Taronyu** [comment]
Steht db0sda denn in der State Datei? Das müsste ja `"db0sda" : { name: "db0sda", ... }` heißen. Das `getNodes().get(...)` erwartet den Knotennamen, so wie er in der State-Datei angegeben ist. Ich bin mir nicht wirklich sicher, was das `toString()` bei dem Address-Object macht. Laut log kommt da ja db0sda raus, also müsste das eigentlich so funktionieren.

**Comment by dh3wr** [comment]
Ist test, moment

**Comment by dh3wr** [comment]
Wobei interessanter Weise der db0wa, der sich hinzuverbinden soll, natürlich nicht den db0sda in seiner noch leeren State.json finden kann. Also vielleicht ist der Fehler, dass bei einem initialen Verbindungsaufbau nach nodes gesucht wird, die aber noch nicht übertragen wurden. Ich kopiere mal die State.json von db0sda auf db0wa und schaue mal

**Comment by dh3wr** [comment]
Update: Das Kopieren hat geholfen. Es ist also ein Initialisierungs-Problem von leeren neuen Knoten ohne Konfig.

**Comment by Taronyu** [comment]
Ja gut, dann kann der natürlich nichts finden, wenn das in seiner lokalen State.json nicht auftaucht. Das ist dann aber ein Henne-Ei-Problem: Der Knoten kann keine aktuelle State.json ziehen, weil er sich nicht authentifizieren kann und er kann sich nicht authentifizieren, weil er keine aktuelle State.json hat. Hmm... so ad hoc fällt mir da nichts zu ein, da ich mich nicht mit diesem jgroups auskenne.

**Comment by dh3wr** [comment]
Noch was
````
.cluster.ClusterManager - Cluster has Quorum
17:08:29.226 [Thread-10] INFO  org.dapnet.core.model.State - Successfully wrote state to file
17:08:32.742 [TransferQueueBundler,DAPNET1.1.0.0,db0sda] ERROR org.jgroups.protocols.TCP - JGRP000029: db0sda: failed sending message to db0rta (235 bytes): java.lang.NullPointerException, headers: GMS: GmsHeader[MERGE_RSP]merge_id=db0rta::3, UNICAST3: DATA, seqno=13, conn_id=4, AUTH: token=org.dapnet.core.cluster.ClusterAuthentication@781d8947, TP: [cluster_name=DAPNET1.1.0.0]
17:09:02.124 [Thread-11] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0sda|8] (3) [db0sda, db0wa, db0rta]
17:09:02.125 [Thread-11] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of db0rta from UNKNOWN to ONLINE
17:09:02.125 [Thread-11] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
17:09:02.130 [Thread-11] INFO  org.dapnet.core.model.State - Successfully wrote state to file
````

**Comment by Taronyu** [comment]
Sagt mir jetzt nichts. Und ich sehe auch nicht, welches Objekt da null sein könnte. Kann wieder alles mögliche sein...

**Comment by dh3wr** [comment]
Wenn man die State.json direkt kopiert geht es.

**Comment by DanielSialkowski** [comment]
Die authenticate Funktion wird beim Clusterleader aufgerufen und nicht beim Knoten, der versucht dem Cluster beizutreten. Dementsprechend gibt es auch eigentlich keine Henne-Ei-Problem und man braucht normalerweise auch keine State.json von Hand zu kopieren. Nur der Clusterleader muss den neuen Knoten in seiner State.json haben, kann anhand dessen den neuen Knoten verifizieren, der dann dem Cluster beitritt und als erstes seine eigene State.json herunterlädt.

Was genau wurde den zuletzt verändert?

**Comment by Taronyu** [comment]
Okay, so genau habe ich mich mit dem jgroups noch nicht befasst.

Meine Vermutung ist aktuell, dass das `getNodes().get(...)` mit dem `IpAddress.toString()` nicht sauber funktioniert. Wie gesagt, das ist eine Map die erwartet den Knotennamen. Wenn da was anderes kommt, findet der nichts.

**Comment by DanielSialkowski** [comment]
Wenn ich mir die Logs von oben anschaue, dann scheint es tatsächlich als wenn die Authentifizierung anders herum verlaufen wäre. Das erklärt auch weswegen das kopieren der State.json geholfen hat. So gedacht ist es definitiv nicht...

**Comment by Taronyu** [comment]
Okay, ist das dann eine Einstellung in dieser Cluster XML?

**Comment by dh3wr** [comment]
@DanielSialkowski Moin Daniel, hast du eine Idee?

**Comment by DanielSialkowski** [comment]
Das Problem scheint zu sein, dass sich der alte Knoten beim neuen authentifiziert hat, statt andersherum.
@dh3wr Kannst du das eventuell mit einem zusätzlichen Knoten noch einmal rekonstruieren? Und bitte überprüfe, ob die `initial_hosts` in der `ClusterConfig.xml` auch richtig gesetzt sind. Falls nämlich der neue Knoten keinen gültigen initial host kennt und der alte Knoten hingegen den neuen Knoten in der Konfigurationsdatei hat oder durch das Speichern der vorherigen Verbindungen noch kennt, könnte ich mich vorstellen, dass es eventuell zu diesem Verhalten kommt...

**Comment by Taronyu** [comment]
Ist das jetzt noch einmal aufgetreten?

**Comment by dh3wr** [comment]
Ja, wenn ich einen neuen Knoten mit nicht vorhandener State.json starte kommt:
````
16:42:15.020 [main] ERROR org.dapnet.core.cluster.ClusterManager - Failed to load state from file.
java.io.FileNotFoundException: ../local/data/State.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_121]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_121]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_121]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_121]
        at org.dapnet.core.model.State.readFromFile(State.java:107) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.cluster.ClusterManager.initState(ClusterManager.java:109) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.cluster.ClusterManager.<init>(ClusterManager.java:70) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:70) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:149) [dapnet-core-1.1.3.0.jar:1.1.3.0]
````
und dann
````
16:47:29.240 [main] WARN  org.dapnet.core.cluster.ClusterManager - Creating new empty State
16:47:32.067 [INT-1,DAPNET1.1.3.0,ihflaptop] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda_test failed: Unknown node
16:47:32.837 [INT-1,DAPNET1.1.3.0,ihflaptop] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda_test failed: Unknown node
16:47:33.337 [INT-2,DAPNET1.1.3.0,ihflaptop] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node db0sda_test failed: Unknown node
````

Kopiere ich die aktuelle State.json, geht alles.

**Comment by Taronyu** [comment]
Ich habe mir mal Commits vor meiner Zeit angesehen, der Code ist aber weitestgehend unverändert. Ich kann das Problem auf jeden Fall reproduzieren. Was mir auffällt, sind die WARNINGS von JGroups über Timeouts in meinem Setup:
```
14:58:33.172 [main] WARN  org.jgroups.protocols.pbcast.FLUSH - dl6pt_dev2: waiting for UNBLOCK timed out after 2000 ms
14:58:36.197 [main] WARN  org.jgroups.protocols.pbcast.GMS - dl6pt_dev2: JOIN(dl6pt_dev2) sent to dl6pt_dev timed out (after 3000 ms), on try 1
...
```

Bevor ich den Master-Knoten nicht zu der State.json des Slaves hinzugefügt hatte, ging da überhaupt nichts mehr. Danach konnte ich mich verbinden, der Slave erhält dann aber nicht den State des Masters. Der Master bleibt hier erst einmal hängen:
```
14:58:38.735 [OOB-1,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev] INFO  org.dapnet.core.cluster.MessageListener - Start sending State to other Node
```

Das sieht irgendwie nach einem Deadlock aus. Wenn ich den Slave dann abschieße gibt es auch noch ein paar Errors, da der das Runterfahren der Nodes an seine Partner verteilen will. Das wird wohl noch eine Weile dauern...

**Comment by Taronyu** [comment]
Ich habe jetzt mal TRACE Logging auf dem Knoten aktiviert, der meinem Cluster beitreten möchte:
```
10:25:31.406 [main] DEBUG org.jgroups.protocols.pbcast.GMS - dl6pt_dev2: sending JOIN(dl6pt_dev2) to dl6pt_dev
10:25:31.408 [main] TRACE org.jgroups.protocols.UNICAST3 - dl6pt_dev2: created sender window for dl6pt_dev (conn-id=0)
10:25:31.409 [main] TRACE org.jgroups.protocols.UNICAST3 - dl6pt_dev2 --> DATA(dl6pt_dev: #1, conn_id=0, first)
10:25:31.410 [main] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: sending msg to dl6pt_dev, src=dl6pt_dev2, headers are GMS: GmsHeader[JOIN_REQ]: mbr=dl6pt_dev2, UNICAST3: DATA, seqno=1, first, AUTH: token=org.dapnet.core.cluster.ClusterAuthentication@3d484181, TP: [cluster_name=DAPNET1.1.3.1-SNAPSHOT]
10:25:31.412 [TransferQueueBundler,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: sending 1 msgs (170 bytes (0.27% of max_bundle_size) to 1 dests(s): [DAPNET1.1.3.1-SNAPSHOT:dl6pt_dev]
10:25:31.413 [TransferQueueBundler,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dest=xxx.xxx.xxx.21:7800 (173 bytes)
10:25:31.673 [INT-2,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: received [dst: <null>, src: dl6pt_dev (2 headers), size=0 bytes, flags=INTERNAL], headers are FD_SOCK: I_HAVE_SOCK, mbr=dl6pt_dev, sock_addr=xxx.xxx.xxx.21:50428, TP: [cluster_name=DAPNET1.1.3.1-SNAPSHOT]
10:25:31.676 [INT-2,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.FD_SOCK - dl6pt_dev2: i-have-sock: dl6pt_dev --> xxx.xxx.xxx.21:50428 (cache is dl6pt_dev2: xxx.xxx.xxx.21:50445 (2 secs old)dl6pt_dev: xxx.xxx.xxx.21:50428 (0 ms old))
10:25:31.674 [INT-1,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: received [dst: dl6pt_dev2, src: dl6pt_dev (2 headers), size=0 bytes, flags=INTERNAL], headers are FD_SOCK: WHO_HAS_SOCK, mbr=dl6pt_dev2, TP: [cluster_name=DAPNET1.1.3.1-SNAPSHOT]
10:25:31.684 [INT-1,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.FD_SOCK - dl6pt_dev2: who-has-sock dl6pt_dev2
10:25:31.684 [INT-1,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: sending msg to dl6pt_dev, src=dl6pt_dev2, headers are FD_SOCK: I_HAVE_SOCK, mbr=dl6pt_dev2, sock_addr=xxx.xxx.xxx.21:50445, TP: [cluster_name=DAPNET1.1.3.1-SNAPSHOT]
10:25:31.685 [TransferQueueBundler,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: sending 1 msgs (101 bytes (0.16% of max_bundle_size) to 1 dests(s): [DAPNET1.1.3.1-SNAPSHOT:dl6pt_dev]
10:25:31.686 [TransferQueueBundler,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dest=xxx.xxx.xxx.21:7800 (104 bytes)
10:25:31.690 [FD_SOCK acceptor,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.FD_SOCK - dl6pt_dev2: accepted connection from /xxx.xxx.xxx.21:50447
10:25:31.914 [INT-2,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.TCP - dl6pt_dev2: received [dst: dl6pt_dev2, src: dl6pt_dev (2 headers), size=0 bytes, flags=INTERNAL], headers are UNICAST3: ACK, seqno=1, ts=1, TP: [cluster_name=DAPNET1.1.3.1-SNAPSHOT]
10:25:31.916 [INT-2,DAPNET1.1.3.1-SNAPSHOT,dl6pt_dev2] TRACE org.jgroups.protocols.UNICAST3 - dl6pt_dev2 <-- ACK(dl6pt_dev: #1, conn-id=0, ts=1)
10:25:34.413 [main] WARN  org.jgroups.protocols.pbcast.GMS - dl6pt_dev2: JOIN(dl6pt_dev2) sent to dl6pt_dev timed out (after 3000 ms), on try 1
```
Nach dem Timeout kommt dann die Auth-Fehlermeldung. Das spielt dann eine Weile Ping-Pong, bis ich den Slave abschieße.

**Comment by Taronyu** [comment]
Ich habe mir das gestern noch einmal recht intensiv angesehen, inklusive Code aus dem JGroups AUTH Protokoll. So wie ich das jetzt verstanden habe, kann das in der hier implementierten Form gar nicht funktionieren. Der neue Knoten muss sich zwar beim Clusterleader authentifizieren, anschließend schickt dieser aber auch ein AuthToken an den neuen Knoten, damit dieser den Leader validieren kann. Und der neue Knoten hat ja noch gar keinen State, in dem er den Key des Leaders nachgucken könnte, denn der State-Transfer erfolgt ja erst nach erfolgter Authentifizierung.

**Comment by Taronyu** [comment]
Ich würde als Workaround auf JGroups SimpleToken umstellen:
```
<AUTH auth_class="org.jgroups.auth.SimpleToken"
auth_value="einPasswort"/>
```
Das muss dann bei allen Knoten eingetragen werden.

**Comment by dh3wr** [comment]
Was ist dann mit der Auth Key-Eigenschaft in der REST API? Ist die dann hinfällig?

**Comment by Taronyu** [comment]
Erst einmal ja. Ich lasse das auch erst einmal alles drinnen, vielleicht finden wir noch eine Lösung.

**Comment by dh3wr** [comment]
Geht jetzt, die Auth-Key-Eigenschaft kann dann wegfallen. Wir haben jetzt das Pre Shared Key Passwort und das reicht dann. Beispiel-Konfig ist geändert.

**Comment by Taronyu** [comment]
Also doch komplett entfernen und wir bleiben bei PSKs?

**Comment by dh3wr** [comment]
Ja, die Eigenschaft eines Konten komplett entfernen

**Comment by Taronyu** [comment]
Der Key ist weg, ebenso die ClusterAuthentication Klasse. Die funktioniert ohne die Eigenschaft nämlich eh nicht mehr. Wir bleiben dann also erst einmal beim SimpleToken zur Authentifizierung.

**Comment by dh3wr** [comment]
ok super, danke
