### ISSUE TITLE
IP, Port und Gerätetyp werden nicht im Cluster verteilt

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#57]
Bei nicht-lokalen Sendern werden die neuen Eigenschaften IP, Port und Gerätetyp werden nicht im Cluster verteilt. Es gibt da Methoden zum senden von Inhalten in den Cluster-Klassen; wahrscheinlich muss das noch hinzugefügt werden.
![grafik](https://cloud.githubusercontent.com/assets/16710361/23342051/3dfe5a4a-fc53-11e6-9b10-c7bb9b18e84f.png)

**Comment by dh3wr** [comment]
Ja, so ist es: Beispiel Nicht-lokal dk5rta:
````
    "dk5rta": {
      "name": "dk5rta",
      "authKey": "XXXXX",
      "longitude": "11.537583",
      "latitude": "48.175588",
      "power": "0.012",
      "nodeName": "db0rta",
      "timeSlot": "0123456789ABCDEF",
      "ownerNames": [
        "dk5rta"
      ],
      "status": "ONLINE",
      "antennaAboveGroundLevel": 0,
      "antennaType": "OMNI",
      "antennaDirection": 0,
      "antennaGainDbi": 0.0,
      "usage": "PERSONAL"
    },
````
Es fehlen die Einträge:
````
     "address": {
        "ip_addr": "44.225.4.131",
        "port": 1337
      },
````

**Comment by dh3wr** [comment]
Bei jeder Änderung des Verbindungsstatuses eines Sender müsste man diese Infos verteilen. Das ist wahrscheinlich vorher nicht geschehen, weil diese Daten ja statisch waren und höchstens beim Anlegen oder Ändern eines Sender verteilt wurden.

**Comment by Taronyu** [comment]
Wenn sich der Sender verbindet, dann werden die Verbindungsdaten erfasst und sollten auch gespeichert werden.

```
private void handleAuth(ChannelHandlerContext ctx, String msg) throws Exception {
	// ...

	Transmitter t = manager.get(name);
	if (t == null) {
		throw new TransmitterException("The transmitter name is not registered.");
	} else if (t.getStatus() == Status.DISABLED) {
		logger.error("Transmitter is disabled and not allowed to connect.");
		ctx.close();
		return;
	} else if (t.getStatus() == Status.ONLINE) {
		// TODO Close existing connection?
		logger.error("Transmitter is already connected.");
		ctx.close();
		return;
	}

	// ...

	t.setDeviceType(type);
	t.setDeviceVersion(version);
	t.setAddress(new IpAddress((InetSocketAddress) ctx.channel().remoteAddress()));

	// ...
}
```
Damit wird auch der Transmitter aktualisiert und beim nächsten Speichern des States auch in die State.json geschrieben. Ich befürchte, dass Updates an Objekten gar nicht weiterverteilt werden, zumindest nicht im laufenden Betrieb ohne Neueinlesen der State-Datei. Das würde natürlich jetzt größere Probleme verursachen.

**Comment by Taronyu** [comment]
Ich habe mal was im `experimental` Branch gebastelt. Magst du das mal ausprobieren?

**Comment by dh3wr** [comment]
Habe es bei DB0SDA und DB0WA installiert, DB0RTA wird noch nachgezogen.

**Comment by dh3wr** [comment]
Läuft.
