### ISSUE TITLE
Core und Rustpager kommen mit Wechsel von dynamischen IP-Adresse nicht klar

### ISSUE THREAD

**Issue by daccle** [DecentralizedAmateurPagingNetwork/Core#58]
Mein Transmitter (dc2zp) auf der Basis von Rustpager geht nach einem Wechsel der IP (dynamische IP von DB0FHN/VPN) in den State Error bei der Transmitter-Übersicht. Das Problem lässt sich durch einen Neustart von Rustpager beheben.

Wie kann rausfinden ob das ein Rustpager oder ein Dapnet Problem ist?

Siehe auch: https://github.com/rwth-afu/RustPager/issues/36

**Comment by dh3wr** [comment]
Zur Klärung: Die sich wechselnde IP ist die des Senders. Ich denke, dass die alte Verbindung nicht sauber getrennt wird und daher der Status nach Error geht.

**Comment by Taronyu** [comment]
Wenn das Neuverbinden direkt nach dem Wechsel stattfindet, wird die TCP-Verbindung im Core wahrscheinlich noch auf einen Timeout warten. Und das kann dauern. Das kann man auch nicht abfangen, da die alte IP ja nicht mehr gültig ist. Aktuell wird eine Verbindung abgewiesen, wenn der Transmitter schon als verbunden gilt. Da habe ich auch schon ein TODO an der Stelle, ob das so laufen soll. Ich habe das im experimental Branch mal umgebaut, jetzt wird die bestehende Verbindung geschlossen, wenn eine neue Verbindung angenommen wird.

**Comment by dh3wr** [comment]
Ist bei db0sda und db0wa eingebaut.
