### ISSUE TITLE
Provide valid logging settings file

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#59]
Zur Zeit wird alles auf die Konsole geschrieben. Das ist recht unübersichtlich, da die ganzen REST-API-Meldungen viel Spam erzeugen. Schön wäre ein Beispiel, welches die REST Sachen in ein separates File schreibt und alles andere sowohl auf die Konsole als auch in eine Datei. Dann kann man die Sender-Verbindungen besser debuggen. Danke.

**Comment by Taronyu** [comment]
Das kann man über die [Config](https://logging.apache.org/log4j/2.x/manual/configuration.html) von log4j lösen. Vom Prinzip her müsste man über den Namen des jeweiligen Loggers filtern können. Außerdem kann man die Loglevels anpassen, um den Spam einzuschränken.

**Comment by dh3wr** [comment]
Zumindest für den REST Kram wäre es gut, diesen weg zu haben.

**Comment by Taronyu** [comment]
Wie gesagt, separates Log Target (Appender) in der Config einrichten und dem Logger zuweisen (AppenderRef) und gut ist.

**Comment by Taronyu** [comment]
Funktioniert das mit der Logconfig bei euch überhaupt? Ich bekomme immer die Meldung, dass keine log4j2 Config gefunden wird obwohl die Datei da ist.

**Comment by Taronyu** [comment]
So, die Logdatei wird nun geladen und ein Default ist auch in der JAR enthalten. Wenn man die LogSettings.xml unter config nutzen will, muss man beim Start `-Dlog4j.configurationFile=config/LogSettings.xml` an die JVM übergeben. Wenn ich das direkt im Programm hinterlege und die Datei existiert nicht, zickt das Logging rum.

**Comment by dh3wr** [comment]
Moin, Habe ich jetzt auf db0sda und db0wa installiert. Läuft. Nur noch eine dumme Frage: Wie kann man eine zusätzliche Log-Datei machen, die alles außer den RESTAPI-Meldungen enthält?

**Comment by Taronyu** [comment]
Ich habe hier mal schnell ein Beispiel zusammengestrickt:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
	<Appenders>
		<Console name="Console" target="SYSTEM_OUT">
			<PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
		</Console>
		<RollingFile name="RestLog" fileName="logs/DAPNET_CORE_REST.log"
			filePattern="logs/DAPNET_CORE_REST-%d{MM-dd-yyyy}.log.gz"
			ignoreExceptions="false">
			<PatternLayout>
				<Pattern>%d %p %c [%t] %m%n</Pattern>
			</PatternLayout>
			<TimeBasedTriggeringPolicy />
		</RollingFile>
	</Appenders>
	<Loggers>
		<Root level="info">
			<AppenderRef ref="Console"/>
		</Root>
		<Logger name="org.dapnet.core.rest.CustomLoggingFilter" level="info" additivity="false">
			<AppenderRef ref="RestLog"/>
		</Logger>
	</Loggers>
</Configuration>
```
Die Datei dann beim Start mit "-Dlog4j.configurationFile=Datei" einbinden.

**Comment by dh3wr** [comment]
Die REST-Meldungen kommen immer noch auf die Konsole.

**Comment by Taronyu** [comment]
Hast du es mal nur mit meiner Logconfig probiert? Mit der von mir geposteten Config und dem Aufruf `java -Dlog4j.configurationFile=config/LogSettings2.xml -jar .\dapnet-core-1.1.0-SNAPSHOT.jar` erhalte ich alle Meldungen außer REST auf die Konsole und die REST-Meldungen gehen in die Datei. Ich weiß jetzt nicht, was in deiner config sonst noch drinnensteht.

**Comment by dh3wr** [comment]
Interessant, jetzt geht`s. Dann war ich wohl zu dumm...
