### ISSUE TITLE
Bei Passwörtern von Sendern keine nur [A-Za-z0-9] erlauben

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#60]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/43

Leerzeichen am Ende könnten Ärger mit dem Regex machen, oder? Vielleicht fangen wir das auch in der RESTAPI ab.

**Comment by Taronyu** [comment]
Leerzeichen gehen gar nicht. Das macht das Pattern kaputt. Im Core ist das momentan "\p{Graph}", das sind alle druckbaren Zeichen.

**Comment by dh3wr** [comment]
Im Web ist das jetzt geändert, vielleicht zur Sicherheit auch im Core?

**Comment by Taronyu** [comment]
Dann muss man das aber gut kommunizieren, welche Zeichen zugelassen sind. Ich würde das im REST Handler dann auch noch prüfen, damit man hintenherum nicht doch noch ein anderes Passwort vergeben kann.

**Comment by dh3wr** [comment]
Bei Eingabe von "weisweiler" als Passwort kommt 4060 Not Acceptable. Passwörter mit einem Buchstaben gehen. Mehr als 1 Buchstabe gibt 4060. Das scheint vom Core zu kommen?

**Comment by dh3wr** [comment]
Regex im Web ist nun /(^[a-zA-Z0-9]+$)/g

**Comment by dh3wr** [comment]
Fixed in c5c20ae93577f6dde857e83ea75f79c14e3ec7db
