### ISSUE TITLE
Invalide Welcome-Message im Log ausgeben

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#61]
Für's Debuggen der Senderanbindung wäre es sehr schön, wenn man die als fehlerhafte Meldung qualifizierte Welcome-Message im Log ausgibt. Dann muss man nicht immer mit tcpdump rumhampeln. Danke sehr.

**Comment by Taronyu** [comment]
Das Passwort wäre dann im Klartext in den Logfiles. Wenn das OK ist, dann kann ich das einbauen.

**Comment by dh3wr** [comment]
Wäre ok
