### ISSUE TITLE
Nicht-Admins bekommen Fehlermeldung von Sender-Tabelle

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#62]
Es mag im Core oder im Web liegen, aber wenn ein Nicht-Admin sich einlogt, bekommt er:

````DataTables warning: table id=tableTransmitters - Requested unknown parameter 'deviceType' for row 7, colum4. [....] ````

das liegt wohl an den neuen Sendereigenschaften. Im besten Fall sind die für Besitzer RW und für alle anderen RO. Oder es liegt daran, dass die nicht richtig bei allen noch nie im neuen Modus verbundenen Sendern in der Datenbank stehen.

**Comment by dh3wr** [comment]
Aha, row 7 hat gar keinen Sendertyp, wenn dies die richtige Row-Nummer ist: db0iga . Als Admin kommt aber keine Fehlermeldung.

**Comment by Taronyu** [comment]
By the way: Kann es sein, dass man sich nur über das HAMNET anmelden kann? Ich komme zwar auf hampager.de, Anmelden erzählt mir dann aber was von API-Fehler. Das funktionierte vorher mal.

**Comment by dh3wr** [comment]
Gut das du's sagst. Mit dem Umzug auf die VM hatte ich den API-Server nicht auf www.hampager.de umgestellt und auch die NAT Roule nicht geändert. Da ich aber auch im HAMNET verbunden war, fiel das nicht auf. Fixed now.

**Comment by Taronyu** [comment]
Ah, cool 👍

**Comment by Taronyu** [comment]
Ich habe gerade mal bei einem meiner Transmitter in der State.json das Feld deviceType gelöscht. Es wurde dann von der REST-API also `"deviceType": null` serialisiert. Das Feld ist also `null` wenn es nicht existiert. Der Validator greift beim Laden nicht ein, da das Feld tatsächlich null sein darf, genau wie deviceVersion.

**Comment by MarvinMenzerath** [comment]
Ich habe das Ganze gerade reproduzieren können:
als Admin eingeloggt erhält man z.B. bei `db0ai` als `deviceType` und `deviceVersion` tatsächlich `null`; als normaler User eingeloggt werden die Elemente gar nicht übertragen und DataTables beschwert sich dementsprechend über die fehlenden Werte.

**Comment by dh3wr** [comment]
Also ist das eine Core-Sache, dass die Angaben bei Nicht-Admins nicht übertragen werden. Please fix :)

**Comment by Taronyu** [comment]
Ich habe den Fehler gefunden, Fix ist in Arbeit.

**Comment by Taronyu** [comment]
Also das Problem war, dass der userGsonBuild KEIN serializeNulls() hatte, der Admin-Builder hingegen schon. Ist im experimental Branch gefixt.

**Comment by dh3wr** [comment]
Geht! Thanks!
