### ISSUE TITLE
Hinzufügen von Knoten liefert UUID statt Namen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#63]
Es kommt raspberry.db0rta nach Update hinzu. Dann Folgendes. Warum 

> New View: [db0sda|5] (4) [db0sda, db0wa, db0rta, 2e421917-b278-e1ff-334e-d745b1c5c13d]

zunächst?

````
10:15:06.781 [Thread-7] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0sda|5] (4) [db0sda, db0wa, db0rta, 2e421917-b278-e1ff-334e-d745b1c5c13d]
10:15:06.784 [Thread-7] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:15:06.838 [Thread-7] INFO  org.dapnet.core.model.State - Successfully wrote state to file
10:16:00.002 [DefaultQuartzScheduler_Worker-7] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to all connected transmitters.
10:16:15.430 [Incoming-1,DAPNET1.1.0.0,db0wa] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus db0el: OK
10:16:22.019 [Incoming-2,DAPNET1.1.0.0,db0wa] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus db0el: OK
10:17:51.930 [Thread-8] INFO  org.dapnet.core.cluster.MembershipListener - New View: MergeView::[raspberry.db0rta|7] (4) [raspberry.db0rta, db0sda, db0wa, db0rta], 2 subgroups: [raspberry.db0rta|6] (1) [raspberry.db0rta], [db0sda|5] (4) [db0sda, db0wa, db0rta, raspberry.db0rta]
10:17:51.933 [Thread-8] INFO  org.dapnet.core.cluster.MembershipListener - Starting merge process
10:17:51.937 [Thread-8] INFO  org.dapnet.core.cluster.MembershipListener - Node is in majorSubgroup: Nothing to be done
10:17:51.939 [Thread-8] INFO  org.dapnet.core.cluster.MembershipListener - Finished merge process
10:17:51.941 [Thread-8] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of raspberry.db0rta from SUSPENDED to ONLINE
10:17:51.942 [Thread-8] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:17:52.039 [Thread-8] INFO  org.dapnet.core.model.State - Successfully wrote state to file
10:18:00.004 [DefaultQuartzScheduler_Worker-8] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to all connected transmitters.
````

**Comment by Taronyu** [comment]
Das `toString()` in der View.java von JGroups liefert eine GUID. Bei uns wird `logger.info("New View: " + view);` aufgerufen, was in einem Aufruf der oben erwähnten `toString()` Methode resultiert, bzw der Methode in einer abgeleiteten Klasse. Ich sehe momentan echt nicht, wo die Klartextnamen herkommen.

**Comment by dh3wr** [comment]
@DanielSialkowski Daniel, kannst du dazu etwas sagen?

**Comment by DanielSialkowski** [comment]
Ja, an der Stelle hat mich JGroups auch sehr verwirrt. Ich habe die `toString()` Methode als einzigen Weg entdeckt an den Knotennamen zu kommen. Mag sein, dass es da einen besseren Weg gibt. Bei der Initalisierung des ClusterManagers wird mit der Zeile `channel.setName(getNodeName());` der Name des Knotens gesetzt. Wird bei einem anderen Knoten nun auf dem UUID Objekt `to String()` aufgerufen wird auch dieser Name anstelle der eigentlichen JGroups UUID zurückgegeben. Tritt ein Knoten dem Cluster regulär bei wird der Name wohl auch direkt ausgetauscht und die `toString()` Methode liefert den richtigen Namen. Tritt der neue Knoten jedoch durch einen Merge bei (wie in den Logs oben) wird der Name wohl erst später ausgetauscht und zunächst wird die UUID angezeigt.

Soweit ich das überblicke sollte das zu keinem Problem führen (abgesehen von dem missverständlichen Log).

**Comment by Taronyu** [comment]
Ad hoc fällt mir jedenfalls auch nichts dazu ein, außer zu beobachten, ob das doch noch zu Problemen führt.
