### ISSUE TITLE
Minor: Beim Start lebt der Port 43434 bevor die Datenbank geladen ist

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#64]
Eher unwichtig, beim Start bekommt man Fehlermeldungen, wenn sich die Sender schon verbinden wollen, die Datenbank aber wohl noch nicht geladen ist. Vielleicht kann man den Port erst zum Ende des Startens aufmachen?

**Comment by Taronyu** [comment]
Der Server wird jetzt ganz zum Schluss gestartet.
