### ISSUE TITLE
JSON Serialisierung beim Abruf aller Transmitter nach dem Start des Cores dauert sehr lange

### ISSUE THREAD

**Issue by Taronyu** [DecentralizedAmateurPagingNetwork/Core#66]
Wenn ich meinen Core lokal starte und dann erstmalig die Liste aller Transmitter ("/transmitters") über die REST-API abrufe, dauert das über 20 Sekunden. Mein Client rennt dabei schon in ein ReadTimeout und macht die Verbindung zu, was dann der Core auch irgendwann mit einer Exception quittiert. Ich habe das schon darauf eingegrenzt, dass der Aufruf `getExclusionGson(status).toJson(object);` schlappe 20 Sekunden laut Log dauert. Beim nächsten Aufruf sind die Daten aber sofort da. Ist euch das auch schon mal aufgefallen?

**Comment by DanielSialkowski** [comment]
Ja, ich hatte das auch schonmal beobachtet. Nach einem Neustart des DAPNET war das Problem direkt wieder verschwunden. Auch meine ich, dass es mir bisher nur unter Linux aufgefallen ist.

**Comment by Taronyu** [comment]
Bei mir passiert das unter Windows, damit ist das schon mal unabhängig vom OS. Eventuell muss Gson erst irgendwelchen internen Dinge initialisieren? Bei mir ist es auf jeden Fall reproduzierbar.

**Comment by Taronyu** [comment]
So, ich habe es gefunden:
```
@Override
public void write(JsonWriter writer, T value) throws IOException {
	JsonElement tree = adapter.toJsonTree(value);

	// Add hostname to json output of IpAddress
	if (value instanceof IpAddress) {
		String host = ((IpAddress) value).getIpAddress().getHostName();
		JsonObject jo = (JsonObject) tree;
		jo.addProperty("hostname", host);
	}

	gson.getAdapter(JsonElement.class).write(writer, tree);
}
```
Der macht für jede IP-Adresse einen Reverse DNS Lookup, das ist eher uncool.
