### ISSUE TITLE
Datenbank-Import überdenken

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Core#67]
Der Import der alten Datenbank bringt ein paar Probleme mit sich:
- Einen Haufen Karteileichen, denn Rufzeichen können sich geändert und Skyper den Besitzer gewechselt haben. Einige sind gestern Abend schon aufgefallen, die Dunkelziffer dürfte weit höher sein. 
- Das Webinterface ist gerade auf älteren Rechnern extrem langsam oder stürzt ab, siehe https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/66
- Alle importierten Nutzer, die ich bisher ausprobiert habe, können sich mit der Kombination rufzeichen/rufzeichen anmelden. Damit ist wieder ein Einfallstor für unberechtigte Nutzung geschaffen, besonders, weil hampager.de über das Internet erreichbar ist.

Ich sehe kein Problem darin, dass jeder neue Nutzer einen Registrierungsantrag stellt. Wir haben gegenwärtig 27 Admins und hoch geschätzt 3000 zu erwartende Nutzer. Wenn es eine Minute dauert, einen Nutzer anzulegen, bedeutet das für jeden der Admins eine Arbeitslast von weniger als zwei Stunden, die sich auch noch über Monate verteilt. Diese Arbeitslast kann noch weiter gesenkt werden, indem man den Betreibern der alten Funkrufmaster Adminrechte gibt (was auch noch aus anderen Gründen sinnvoll ist). Die Aktualität der Daten wäre so auf jeden Fall gewärleistet.

**Comment by Taronyu** [comment]
Das Problem mit der #66 habe ich bei nur 116 Usern. Laut meiner Analyse liegt das aber an der Serialisierung der Transmitter und tritt nur nach dem Start des Cores auf, nicht bei späteren Aufrufen. Im aktuellen `master` sind aber unter `/stats` ein paar Statistiken zum Abrufen verfügbar, so dass das nicht über die Webseite berechnet werden muss (siehe #11).

**Comment by dh3wr** [comment]
Weiß jemand, ob http://ans.bundesnetzagentur.de/Amateurfunk/Rufzeichen.aspx alle gültigen Rufzeichen enthält? Dann könnte man schon mal eine Cross-Check machen und dort nicht aufgeführte Rufzeichen löschen.

**Comment by Taronyu** [comment]
Ich war nach zwei Tagen oder so drinnen. Ich meine aber, man sieht da auch noch Rufzeichen, die in der Sperrfrist liegen und noch nicht wieder freigegeben sind.

**Comment by dh3wr** [comment]
Alternative: wir löschen wieder die neuen User und machen auf einer separaten Seite ein Formular und ein Skript, mit dem man sich unter Kenntnis des damals registrierten Rufzeichens freischalten kann. Dann hat keiner Arbeit und es ist trotzdem mit vertretbarem Aufwand für den User möglich, sich zu legitimieren.

**Comment by dj7lc** [comment]
Dein Vorschlag zur Löschung und Freischaltung über ein Webformular erscheint mir sinnvoll. Wenn das mit vertretbarem Aufwand möglich ist, wäre das eine gute Sache.

**Comment by dh3wr** [comment]
Meine Alternative wurde umgesetzt. Siehe http://www.hampager.de/dapnet-import/ und Text auf der Startseite.

**Comment by dj7lc** [comment]
Super! Damit ist die Sache schon wesentlich übersichtlicher.
