### ISSUE TITLE
Tracking uptime of transmitters or last change timestamp

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#69]
Ein bischen Statistik und Hinterground-Info. Vielleicht auch die Anzahl der Ruf-Aussendungen mitschreiben?
Jeweils ab Connect oder ab Mitternacht.

**Comment by Taronyu** [comment]
Ich habe im experimental Branch mal die Zeit, wann die Verbindung hergestellt wurde, eingetragen. Diese wird beim Herstellen der Verbindung auf den aktuellen Zeitstempel in UTC und beim Trennen auf `null` gesetzt (steht beim Transmitter).

Sonstige Statistiken zu einem Transmitter habe ich momentan noch ausgeklammert, ich sehe bei naiven Implementierungen den Overhead beim Sync des States zwischen den Knoten. Ob eine Nachricht auch tatsächlich über das Netzwerk an den Transmitter übertragen wurde, kann ja nur der Knoten sagen, der mit dem Transmitter verbunden ist. Es kann also nicht einfach jeder Knoten bei sich lokal hochzählen, wenn ein Call eingeht, jedenfalls nicht, wenn man auch Fehler mitbekommen möchte. Ein naives Vorgehen wäre, wenn man analog zum Statusupdate eines Transmitters pro gesendeter Nachricht ein Event an alle Knoten aussendet.

Mein Vorschlag wäre aktuell, zwischen Daten, die "sofort" bei allen Knoten verfügbar sein müssen (neue Transmitter beispielsweise) und weniger kritischen Daten ("Transmitter XY hat 4 Nachrichten seit Connect versandt") zu unterscheiden. Letztere würden durch einen Job periodisch an die anderen Knoten geschickt. Ich habe mir aber noch gar nicht angesehen, ob das technisch überhaupt so machbar wäre. Die ganze Nebenläufigkeit spielt da auch noch mit rein. Insofern ist der Vorschlag noch mit Vorsicht zu genießen.

**Comment by dh3wr** [comment]
ok, lass und da mal heute abend drüber reden.

**Comment by Taronyu** [comment]
Es gibt jetzt noch ein zusätzliches Attribute `lastConnected` im Transmitter, das den Zeitpunkt der letzten erfolgreichen Verbindung speichert. Ist allerdings momentan nur im `experimental` Zweig enthalten.
