### ISSUE TITLE
Evaluierung moderner Empfänger als Alternative zum Skyper

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#7]
Finde, dass der Kauf von alten gebrauchten Skypern nicht die optimale Lösung ist. Eventuell könnte man die Kompatibilität mit modernen Pagern testen oder selber etwas basteln (hier könnte man die gesamte Infrastruktur zur Verfügung stellen)...

**Comment by rtausend** [comment]
Dieser kommerzielle Empfänger: http://alphapoc.com/index.php?cPath=2_49
ist für die unterschiedlichsten Frequenzen (auch ISM Band und 436-440MHz) erhältlich und hält sich Preislich noch im rahmen ..

**Comment by Taronyu** [comment]
Das ist ja kein Issue des Cores, ich mach das daher mal zu.
