### ISSUE TITLE
API akzeptiert Transmitter Group auch, wenn Case nicht stimmt, aber keine Reaktion

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#71]
Wenn man in der API eine Transmittergroup namens "All" angibt, die Gruppe aber "all" heißt, wird der Ruf zwar angenommen, aber nicht ausgesendet.
![grafik](https://cloud.githubusercontent.com/assets/16710361/23798311/5d7b92b6-05a4-11e7-953a-df6bd55e4fb7.png)

Vielleicht besser entweder case sensitiv oder nach der API Prozessierung alles in Kleinbuchstaben umwandeln. Hier scheint noch eine Inkonsistenz zu sein.

**Comment by Taronyu** [comment]
Das Problem ist mir schon länger bekannt, ich hatte mir da auch schon Gedanken zu gemacht. Idealerweise muss wäre das komplett case insensitive.

**Comment by Taronyu** [comment]
Magst du die Version aus dem `experimental` Branch probieren? Da sind allerdings noch ein paar andere Änderungen drinnen.

**Comment by dh3wr** [comment]
Heute Abend, bin unterwegs
