### ISSUE TITLE
User können eigene Ressourcen nicht löschen

### ISSUE THREAD

**Issue by MarvinMenzerath** [DecentralizedAmateurPagingNetwork/Core#73]
Ein angemeldeter User kann seine eigenen Ressourcen (z.B. sein Rufzeichen) nicht löschen.
Das ist scheinbar auch bei anderen Ressourcen der Fall.

```json
{
    "code": 4030,
    "name": "Forbidden",
    "message": "No permission for this request"
}
```

**Comment by Taronyu** [comment]
Im master gefixt (14a079033ffd2359901cfed62d76a86e53122c27), habe allerdings die falsche Nummer in der Commit Message angegeben :D

**Comment by MarvinMenzerath** [comment]
Leider bekomme ich immer noch die gleiche Fehlermeldung zurück und kann die Ressource nur als Admin löschen...

**Comment by Taronyu** [comment]
Offenbar funktioniert die Prüfung `isOwner()` nicht richtig, das ist auch das Problem bei #72

**Comment by Taronyu** [comment]
Das scheint nun zu funktionieren. Das Problem war, dass bei "USER_ONLY" der Owner gar nicht erst geprüft wurde. Und bei OWNER_ONLY dürfen sonstige angemeldete User nicht. Ich habe das nun so gelöst, dass der Owner nun immer geprüft wird.

**Comment by dh3wr** [comment]
ich teste auf www.hampager.de

**Comment by MarvinMenzerath** [comment]
Meine Testfälle haben funktioniert, danke!
