### ISSUE TITLE
Core oder Web? : 500 bei http://www.hampager.de:8080/stats

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#76]
Siehe auch https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/49

**Comment by Taronyu** [comment]
Was sagt das Log vom Core dazu?

**Comment by dh3wr** [comment]
````
17-03-14 22:45:24,004 INFO org.dapnet.core.rest.CustomLoggingFilter [grizzly-http-server-1] REST GET Request : User: null - Path: stats - Header: {host=[www.hampager.de:8080], user-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0], accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], accept-language=[de,en-US;q=0.7,en;q=0.3], accept-encoding=[gzip, deflate], cookie=[_pk_id.1.97c9=2ffbc5cd5f6d17d6.1476360736.38.1478529613.1478529613.; auth=ZGgzd3I6ZGUxcmN3], connection=[keep-alive], upgrade-insecure-requests=[1], cache-control=[max-age=0]} - Entity:
````

**Comment by dh3wr** [comment]
Aha: ``[grizzly-http-server-3] INFO  org.dapnet.core.rest.RestSecurity - No Authorization Data in HttpHeader``

**Comment by dh3wr** [comment]
ICh gl

**Comment by Taronyu** [comment]
Das sollte eigentlich auch ohne Auth funktionieren, oder?

**Comment by dh3wr** [comment]
Ja so die Idee

**Comment by dh3wr** [comment]
Ich habe auch noch ``22:53:40.480 [grizzly-http-server-3] INFO  org.dapnet.core.rest.RestSecurity - Wrong Password`` anzubieten. Keine Ahung, ob das jetzt eine neue Meldung ist und jemand ein falsches Passwort eingegeben hat?

**Comment by Taronyu** [comment]
Ich komme beim aktuellen master ohne Authentifizierung auf die Stats-Seite drauf. Wenn man aber mit einem nicht existenten User oder falschem Passwort kommt, gibt es einen Fehler. Wenn die Auth angegeben wird, wird sie also geprüft, selbst wenn die Seite ohne Auth verfügbar wäre.

**Comment by dh3wr** [comment]
aha... ok interessant, dass alle anderen Sachen auf der Seite gehen.
![grafik](https://cloud.githubusercontent.com/assets/16710361/23924182/ecd91d9e-0909-11e7-93e3-c1aff67d06d6.png)

Wieso sollte ich dann einmal eine falsche Auth haben?

**Comment by dh3wr** [comment]
Ebenfalls 500 mit lynx, und da habe ich keine Auth niemals nicht eingegeben.

**Comment by dh3wr** [comment]
``git status`` sagt:
````
commit 7fd2360007a37f4963a2954c56428d174e32a8c2
Author: Philipp Thiel <taronyu@users.noreply.github.com>
Date:   Tue Mar 14 15:37:52 2017 +0100

    More missing @Overrides
````
Ist also aktuell

**Comment by Taronyu** [comment]
Hmm, bei mir läuft das ohne Auth, als normaler User und als Admin. 

```
23:03:34.859 [grizzly-http-server-1] INFO  org.dapnet.core.rest.CustomLoggingFilter - REST GET Request : User: null - Pa
th: stats - Header: {accept-encoding=[gzip,deflate], host=[localhost:8080], connection=[Keep-Alive], user-agent=[Apache-
HttpClient/4.1.1 (java 1.5)]} - Entity:
23:03:34.861 [grizzly-http-server-1] INFO  org.dapnet.core.rest.RestSecurity - No Authorization Data in HttpHeader
23:03:34.863 [grizzly-http-server-1] INFO  org.dapnet.core.rest.CustomLoggingFilter - REST GET Response : Header: {Conte
nt-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Con
tent-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: {  "users": 116
,  "calls": 59,  "callSigns": 89,  "news": 2,  "rubrics": 7,  "nodesTotal": 1,  "nodesOnline": 1,  "transmittersTotal":
45,  "transmittersOnline": 0}
```
Das no auth data kommt übrigens immer wenn die fehlt, das ist nicht für den 500er verantwortlich. Taucht da sonst im Log nichts auf? Der loggt doch sonst jeden Pieps der REST API.

**Comment by dh3wr** [comment]
Nach einem neuen ``git clone`` und ``mvn clean package`` ist das ok. Komisch. Sorry für den Aufwand.

**Comment by Taronyu** [comment]
Kein Problem, ich habe bei mir auch mittlerweile nur noch "clean package" als Goals angegeben, da ich auch schon mal mit alten Dateien Probleme hatte. Das ist die sicherste Variante, auch wenn sich libs geändert haben. Das landet sonst alles in der jar bzw. im zip und kann dann halt Probleme verursachen.
