### ISSUE TITLE
Häufigkeit der Rubrikenlistenaussendung reduzieren

### ISSUE THREAD

**Issue by dj7lc** [DecentralizedAmateurPagingNetwork/Core#77]
Momentan läuft alle fünf Minuten die Rubrikenliste über die Sender. Bei Sendern mit nur zwei Zeitschlitzen führt das zu Verstopfungen und es dauert manchmal mehrere Minuten, bis ein Ruf durchkommt. Ich schlage daher vor, die Liste nur alle 6 Stunden zu übertragen. Das ist noch mehr als ausreichend, so selten wie sich die Liste ändert.

**Comment by Taronyu** [comment]
In der Settings.json des Cores kann man das Intervall angeben:
```
"schedulerSettings": {
    ...
    "rubricNameTransmissionCron": "15 0/20 * * * ?",
    ...
  }
```
So steht das in meiner config und heißt übersetzt: "Sende die Rubriken alle 20 Minuten, 15 Sekunden", also zum Beispiel um 13:00:15, 13:20:15, 13:40:15, ...

Eine kurze Anleitung gibt es [hier](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html).

**Comment by dh3wr** [comment]
Ich hatte es tatsächlich höher gestellt für Testzwecke. Ich stelle es mal auf alle 4 Std.
