### ISSUE TITLE
Keine Verbindung zu den anderen Cores

### ISSUE THREAD

**Issue by stephensworld** [DecentralizedAmateurPagingNetwork/Core#80]
Hallo,

ich hab seit heute ca. 10 Uhr leider keine Verbindung mehr zu den anderen Cores.

Viele Grüße
Stephan

java -jar dapnet-core-1.1.3.0-SNAPSHOT.jar 
20:36:04.189 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNETCore Version 1.1.3.0-SNAPSHOT ...
20:36:04.191 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
20:36:04.400 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
20:36:04.478 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.4.Final
20:36:11.661 [main] FATAL org.dapnet.core.cluster.ClusterManager - Could not connect to cluster
Could not connect to cluster. Check your settings and make sure your node is already registered.
20:36:11.662 [main] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNETCore ...
20:36:11.662 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore stopped
20:36:11.663 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: db0erg
20:36:11.663 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: dg2rbf
20:36:11.663 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: dm0ffl
20:36:11.663 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: db0ffl
20:36:11.664 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: dk9cvb
20:36:11.664 [main] INFO  org.dapnet.core.transmission.TransmitterManager - Transmitter added: dl3rcg
20:36:11.664 [main] INFO  org.dapnet.core.DAPNETCore - Starting SchedulerManager
20:36:11.740 [main] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully started
20:36:11.740 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
20:36:12.356 [main] INFO  org.dapnet.core.rest.RestManager - RestApi successfully started
20:36:12.356 [main] INFO  org.dapnet.core.DAPNETCore - Starting Transmitter Server
20:36:12.357 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore started
20:36:12.484 [Thread-2] INFO  org.dapnet.core.transmission.Server - Server started on port: 43434
20:36:13.552 [nioEventLoopGroup-3-1] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.41.234:52967
20:36:13.868 [nioEventLoopGroup-3-1] ERROR org.dapnet.core.cluster.ClusterManager - Response: 
20:36:13.869 [nioEventLoopGroup-3-1] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
20:36:14.560 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /188.195.148.3:36954
20:36:15.045 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.cluster.ClusterManager - Response: 
20:36:15.047 [nioEventLoopGroup-3-2] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
20:36:15.142 [nioEventLoopGroup-3-3] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /127.0.0.1:49440
20:36:15.527 [nioEventLoopGroup-3-3] ERROR org.dapnet.core.cluster.ClusterManager - Response: 
20:36:15.527 [nioEventLoopGroup-3-3] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
20:36:20.652 [nioEventLoopGroup-3-4] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.41.234:52969
20:36:20.676 [nioEventLoopGroup-3-1] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
20:36:20.677 [nioEventLoopGroup-3-1] ERROR org.dapnet.core.cluster.ClusterManager - Response: 20:36:34.182 [nioEventLoopGroup-3-5] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.41.234:52971
20:36:34.216 [nioEventLoopGroup-3-4] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
20:36:34.216 [nioEventLoopGroup-3-4] ERROR org.dapnet.core.cluster.ClusterManager - Response: 
20:36:34.216 [nioEventLoopGroup-3-4] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
20:36:34.509 [nioEventLoopGroup-3-5] ERROR org.dapnet.core.cluster.ClusterManager - Response: 
20:36:34.510 [nioEventLoopGroup-3-5] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State

**Comment by Taronyu** [comment]
Kannst du mir sagen, welcher Commit das ist ("git log")? Es sieht danach aus, als würde der Remote Procedure Call fehlschlagen (ClusterManager.java:215). Das kann passieren, wenn die Versionen nicht mehr zueinander passen. Entweder deine ist zu neu oder die anderen sind neuer. Das ist zumindest meine Vermutung.

**Comment by stephensworld** [comment]
commit c9c277abc320439b8d7a41811719982c8f7b1f66
Author: Philipp Thiel <taronyu@users.noreply.github.com>
Date:   Mon Mar 20 09:34:54 2017 +0100

    Fixed premature shutdown of logging system.

commit 9634408436ccc2937c5ebffada78dd429a648138
Author: Philipp Thiel <taronyu@users.noreply.github.com>
Date:   Mon Mar 20 09:09:17 2017 +0100

    Added wait for sync to server event loop groups shutdown.

commit faff3a14dee9947f221f539ad846f0721a31a5a3
Author: Philipp Thiel <pthiel@radicalworlds.de>
Date:   Fri Mar 17 07:22:27 2017 +0100

    Added UNKNOWN version number as fallback (see #78)



Ich hab Ralf vorhin noch eine Mail geschickt. Eventuell liegt es an einer Route im Hamnet.

**Comment by Taronyu** [comment]
Wenn sich ein Transmitter verbindet, wird ein Statusupdate an alle Knoten verschickt. Die Methode `handleTransmitterStatusChanged()`  ruft dazu `handleStateOperation()` auf, die das Update an alle Knoten verteilt. Mindestens ein Knoten meldet daraufhin einen Fehler. Leider ist aus dem Log nicht ersichtlich, was da nicht funktioniert. Das könnte aber im Log der anderen Knoten stehen.

**Comment by dh3wr** [comment]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/81

Jedenfalls macht ein angemeldeter Core mit einer nicht direkt erreichbaren IP das ganze Cluster kaputt, so dass man alle Cores beenden muss, die State.json von der 192. er befreien muss, und dann alles wieder starten muss

**Comment by Taronyu** [comment]
Problem ist wohl, dass jgroups die eigene IP mitschickt, diese aber dann von den externen Knoten nicht erreicht werden kann. Dafür gibt es aber einen Parameter `external_addr`, den man in der ClusterConfig angeben kann. Das ist in #81 verlinkt.

**Comment by dh3wr** [comment]
Siehe a80ef784183b74962bee714122ed1e0c8449f411
