### ISSUE TITLE
Cores hinter NAT crashen Cluster

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#81]
Bei DM0MAX haben wir den Zustand, dass der Core auf einer 192.168 IP läuft. Diese ist ausgehend geNATed, aber der Core meldet sich mit deiner 192.er IP an. Die anderen Cores können dahin natürlich keinen Nachrichten schicken.
Mögliche Lösung:

- nur direkt erreichbare Core dürfen mitmachen,
- oder es wird im Core nicht die Interface-IP des Sender-Cores beim Anmelden übernommen, sondern die ankommende Source-IP beim Core, an dem sich der 192.er Core anmeldet. Ob das geht, keine Ahnung

**Comment by dh3wr** [comment]
Noch eine Möglichkeit: Man kann seine eigene IP manuell einstellen und diese wird dann propagiert.

**Comment by Taronyu** [comment]
Das müssen wir uns nachher mal ansehen. Soweit ich das nachverfolgen konnte, wird die IP-Adresse zwar im Knoten gespeichert, aber sonst nirgendwo verwendet. Die Methode `getAddress()` wird gar nicht aufgerufen.

**Comment by Taronyu** [comment]
Da gibt es sogar schon was in jgroups: [external_addr](https://docs.jboss.org/jbossas/docs/Clustering_Guide/beta422/html/jbosscache-jgroups-transport-tcp.html)

**Comment by dh3wr** [comment]
Wird die nicht für die Zusendung der Nachrichten zwischen des Cores benutzt? Ich hatte Meldungen à la "kann rpc call nicht an 192.xx senden"

**Comment by Taronyu** [comment]
Ja, so wie ich das verstanden habe, teilt der Channel den anderen Channeln seine eigene IP beim Merge des Memberships mit. Und das ist nunmal die IP, auf dem der jgroups Server auch läuft. Wie gesagt, die Methode `Node::getAddress()`, die auch aus der State.json kommt, wird im gesamten Projekt kein einziges mal aufgerufen.

**Comment by dh3wr** [comment]
Aha, Zur Zeit steckt ja da nur `` <TCP bind_port="7800"/>``
Kann kann man da die external_addr angeben, richtig?

**Comment by Taronyu** [comment]
So habe ich das verstanden. Die Beschreibung auf der Seite befasst sich ja ziemlich deutlich mit der NAT-Problematik.

**Comment by dh3wr** [comment]
ok, ich teile es mit...

**Comment by phl0** [comment]
Das wird nicht gehen, weil ein bind nur auf tatsächlich auf dem host
vorhandene IP-Adressen funktioniert, denke ich.

**Comment by Taronyu** [comment]
>  specifies external IP address to broadcast to other group members (if different to local address).
Das hört sich für mich aber genauch nach dem hier auftretenden Problem an. Der Server läuft auf der lokalen IP und diese wird dann auch gemeldet. Wenn `external_addr` gesetzt ist, wird stattdessen diese Adresse an die anderen Cores gemeldet. Der Server läuft dann trotzdem auf der lokalen IP, aber das regelt dann ja NAT.

**Comment by dh3wr** [comment]
Hat sich damit wohl erledigt. a80ef784183b74962bee714122ed1e0c8449f411
