### ISSUE TITLE
Sender-Log-Ausgabe verbessern

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#82]
z.B. kam gerade ``org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid sequence number received.``
Wäre super, wenn man den Sendernamen bei diesen Logs ausgeben würde, dann kann man gezielter debuggen. Danke

**Comment by dh3wr** [comment]
Ebenfalls wäre der neue Status hier interessant:
``INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus dm0max: OK``

**Comment by Taronyu** [comment]
Beim UpdateTransmitterStatus wird eine generische Logmethode aufgerufen, da kann ich nicht ohne Weiteres die neuen Daten eintüten. Zumal der Name ein bisschen irreführend ist. In der Methode werden alle dynamischen Eigenschaften eines Senders gesetzt, nicht nur der Status. Es werden auch alle Properties neu gesetzt, egal ob die sich geändert haben oder nicht.
