### ISSUE TITLE
"Pseudo"-Rubriken für Nicht-Skyper

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#87]
DO1OW schreibt:
Guten Abend!

Ich habe eine Frage zu den Rubriken im DAPNET. Wenn ich das richtig
verstanden habe werden die verschiedenen Rubriken auf speziellen RICs
übertragen (4520 bzw. 4512 wenn ich mich recht erinnere). Allerdings ist
der Inhalt nur für Skyper lesbar und auch nur dann, wenn die Rubriken
vorher aktiviert wurden. Leider ist mein alter Skyper ziemlich
unempfindlich und empfängt daher DB0VVS hier nur bruchstückhaft. Ich
habe auch noch einen anderen Pager, in dem 8 individuelle RICS mit
Unteradressen programmierbar sind (Alphapoc 602R). Der Empfang der
"normalen" Nachrichten klappt damit recht zuverlässig, auch wenn ich am
Rand des Versorgungsgiebtes wohne. Aber die Rubriken gehen damit halt
nicht. Ich gehe mal davon aus, dass auch noch andere Nutzer Pager
betreiben, die keine Skyper sind. Wäre es eine Möglichkeit, die
verschiedenen Rubriken im Klartext auf dafür definierte RICs zu senden
(z.B. 4812 für rwth-afu)? Dann könnte man an anderen Pagern die Rubriken
auch empfangen und müsste halt nur die entsprechenden RICs programmieren.

Viele Grüße,

Oliver DO1OW

**Comment by dj7lc** [comment]
Die Problematik ist bekannnt:
https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/68

**Comment by Taronyu** [comment]
Gut, dann mache ich hier mal zu.
