### ISSUE TITLE
Nicht-Admins sollen eigene Rufzeichen anlegen können

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#92]
Entweder Core oder Web, aber ein neu eingerichteter User kann keine neuen Rufzeichen (z.B. für sich) anlegen. Das sollten wir ändern.

**Comment by Taronyu** [comment]
Das Anlegen von Rufzeichen für nicht-Admins hatten wir in #45 gerade abgestellt. Soll ich das wieder ändern?

**Comment by dh3wr** [comment]
Hatte ich schon wieder verpeilt. Wir lassen das erstmal so wie es ist.
