### ISSUE TITLE
Neues Senderflag zur Erstellung von Abdeckungskarten

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#98]
@MarvinMenzerath und ich bauen gerade eine automatische Abdeckungsberechnungen der Senderreichweiten in die Kartendarstellung ein. Um nur geänderte Sender neu zu berechnen, wäre es schön ein ``WasChanged`` boolean flag bei den Sendereigenschaften zu haben. Von Core-Seite wird das bei jedem PUT auf true gesetzt.
Wir brauchen dann eine einfache Methode, mit der das Berechnungsskript dies nach erfolgreicher Neu-Berechnung auf false setzen kann, ohne die anderen Eigeschaften des Senders kennen zu müssen oder diese zu verändern.

**Comment by 7h0ma5** [comment]
Wäre es nicht sinnvoller den Zeitpunkt der letzten Änderung eines Senders zu speichern? Bei der Abdeckungsberechnung kann man dann den Zeitpunkt der Berechnung mit abspeichern und dann später vergleichen, ob eine neue Berechnung notwendig ist.

**Comment by dh3wr** [comment]
ok, guter Vorschlag. Dann so. Und auf NTP hoffen :-)

**Comment by Taronyu** [comment]
An so etwas hatte ich jetzt auch eher gedacht. Ein "LastUpdate" Timestamp oder so.

**Comment by dh3wr** [comment]
ok, ist auch besser, dann muss nichts geändert werden.

**Comment by dh3wr** [comment]
ok, ich teste das mal auf einer Testinstallation und dann kann @MarvinMenzerath schon mal damit arbeiten. Wenn das läuft, dann machen wir ein neues Release und rollen das clusterweit aus.

**Comment by Taronyu** [comment]
Hat sich das eigentlich erledigt?

**Comment by dh3wr** [comment]
@MarvinMenzerath ist noch an der Implementierung dran. Wenn die fertig ist und geht, machen wir das hier zu. Ich denke aber schon.

**Comment by dh3wr** [comment]
Auch wenn der Code nicht danach aussieht:
- [ ] Es wird teilweise nicht das richtige Datum bei Sendern gesetzt, wenn schon eins da ist
- [ ] Wenn ``null`` in der JSON Antwort steht, wird dies nicht geupdatet, wenn man putTransmitter vom Web-Interface aus aufruft.

**Comment by Taronyu** [comment]
Beim Update eines bestehenden Senders über die REST API wird bei jedem PUT das Datum gesetzt (TransmitterRessource.java:86): `transmitter.setLastUpdate(Instant.now());`
Ansonsten wird das Datum noch in der Methode `updateTransmitterStatus()` bei RpcListener.java:465 gesetzt, wobei das nur aus dem aktiven Transmitter übernommen wird. Die Methode wird wiederum nur vom TransmitterManager aufgerufen, der fast das Datum aber gar nicht an.

Hast du für den zweiten Punkt ein Beispiel?

**Comment by Taronyu** [comment]
Das Problem sollte nun behoben sein.

**Comment by MarvinMenzerath** [comment]
Ja, sieht jetzt alles richtig aus :+1:
